/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */



#include "AcesConfig.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




AcesConfig::AcesConfig()
{
    m_Enabled = false;
    m_EnabledIsSet = false;
    m_ModeIsSet = false;
    m_AmfLibraryEntry = 0;
    m_AmfLibraryEntryIsSet = false;
    m_OcioSourceIsSet = false;
    m_OcioDisplayViewIsSet = false;
    m_EnableArriWVOLogC4Decoder = false;
    m_EnableArriWVOLogC4DecoderIsSet = false;
}

AcesConfig::~AcesConfig()
{
}

void AcesConfig::validate()
{
    // TODO: implement validation
}

bool AcesConfig::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	if (amfLibraryEntryIsSet())
	{
		bool amfLibraryEntryChanged = false;
		int32_t v = getAmfLibraryEntry();
		if (amfLibraryEntryChanged) { setAmfLibraryEntry(v); anyMinMaxValueChanged = true; }
	}
	return anyMinMaxValueChanged;
}

web::json::value AcesConfig::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EnabledIsSet)
    {
        val[utility::conversions::to_string_t(U("enabled"))] = ModelBase::toJson(m_Enabled);
    }
    if(m_ModeIsSet)
    {
        val[utility::conversions::to_string_t(U("mode"))] = ModelBase::toJson(m_Mode);
    }
    if(m_AmfLibraryEntryIsSet)
    {
        val[utility::conversions::to_string_t(U("amfLibraryEntry"))] = ModelBase::toJson(m_AmfLibraryEntry);
    }
    if(m_OcioSourceIsSet)
    {
        val[utility::conversions::to_string_t(U("ocioSource"))] = ModelBase::toJson(m_OcioSource);
    }
    if(m_OcioDisplayViewIsSet)
    {
        val[utility::conversions::to_string_t(U("ocioDisplayView"))] = ModelBase::toJson(m_OcioDisplayView);
    }
    if(m_EnableArriWVOLogC4DecoderIsSet)
    {
        val[utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder"))] = ModelBase::toJson(m_EnableArriWVOLogC4Decoder);
    }

    return val;
}

bool AcesConfig::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("enabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("enabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_enabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_enabled);
            setEnabled(refVal_enabled);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("mode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("mode")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AcesMode> refVal_mode;
            ok &= ModelBase::fromJson(fieldValue, refVal_mode);
            setMode(refVal_mode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("amfLibraryEntry"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("amfLibraryEntry")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_amfLibraryEntry;
            ok &= ModelBase::fromJson(fieldValue, refVal_amfLibraryEntry);
            setAmfLibraryEntry(refVal_amfLibraryEntry);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ocioSource"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ocioSource")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<OcioSource> refVal_ocioSource;
            ok &= ModelBase::fromJson(fieldValue, refVal_ocioSource);
            setOcioSource(refVal_ocioSource);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ocioDisplayView"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ocioDisplayView")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<OcioDisplayView> refVal_ocioDisplayView;
            ok &= ModelBase::fromJson(fieldValue, refVal_ocioDisplayView);
            setOcioDisplayView(refVal_ocioDisplayView);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder")));
        if(!fieldValue.is_null())
        {
            bool refVal_enableArriWVOLogC4Decoder;
            ok &= ModelBase::fromJson(fieldValue, refVal_enableArriWVOLogC4Decoder);
            setEnableArriWVOLogC4Decoder(refVal_enableArriWVOLogC4Decoder);
        }
    }
    
    applyMinMaxConstraints();
    return ok;
}

void AcesConfig::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_EnabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("enabled")), m_Enabled));
    }
    if(m_ModeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("mode")), m_Mode));
    }
    if(m_AmfLibraryEntryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("amfLibraryEntry")), m_AmfLibraryEntry));
    }
    if(m_OcioSourceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ocioSource")), m_OcioSource));
    }
    if(m_OcioDisplayViewIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ocioDisplayView")), m_OcioDisplayView));
    }
    if(m_EnableArriWVOLogC4DecoderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder")), m_EnableArriWVOLogC4Decoder));
    }
}

bool AcesConfig::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("enabled"))))
    {
        bool refVal_enabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("enabled"))), refVal_enabled );
        setEnabled(refVal_enabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("mode"))))
    {
        std::shared_ptr<AcesMode> refVal_mode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("mode"))), refVal_mode );
        setMode(refVal_mode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("amfLibraryEntry"))))
    {
        int32_t refVal_amfLibraryEntry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("amfLibraryEntry"))), refVal_amfLibraryEntry );
        setAmfLibraryEntry(refVal_amfLibraryEntry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ocioSource"))))
    {
        std::shared_ptr<OcioSource> refVal_ocioSource;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ocioSource"))), refVal_ocioSource );
        setOcioSource(refVal_ocioSource);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ocioDisplayView"))))
    {
        std::shared_ptr<OcioDisplayView> refVal_ocioDisplayView;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ocioDisplayView"))), refVal_ocioDisplayView );
        setOcioDisplayView(refVal_ocioDisplayView);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder"))))
    {
        bool refVal_enableArriWVOLogC4Decoder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("enableArriWVOLogC4Decoder"))), refVal_enableArriWVOLogC4Decoder );
        setEnableArriWVOLogC4Decoder(refVal_enableArriWVOLogC4Decoder);
    }
    
    applyMinMaxConstraints();
    return ok;
}

bool AcesConfig::isEnabled() const
{
    return m_Enabled;
}

void AcesConfig::setEnabled(bool value)
{
	bool v = value;
    m_Enabled = v;
    m_EnabledIsSet = true;
}

bool AcesConfig::enabledIsSet() const
{
    return m_EnabledIsSet;
}

void AcesConfig::unsetEnabled()
{
    m_EnabledIsSet = false;
}


std::shared_ptr<AcesMode> AcesConfig::getMode() const
{
    return m_Mode;
}

void AcesConfig::setMode(const std::shared_ptr<AcesMode>& value)
{
	std::shared_ptr<AcesMode> v = value;
    m_Mode = v;
    m_ModeIsSet = true;
}

bool AcesConfig::modeIsSet() const
{
    return m_ModeIsSet;
}

void AcesConfig::unsetMode()
{
    m_ModeIsSet = false;
}


int32_t AcesConfig::getAmfLibraryEntry() const
{
    return m_AmfLibraryEntry;
}

void AcesConfig::setAmfLibraryEntry(int32_t value)
{
	int32_t v = value;
    m_AmfLibraryEntry = v;
    m_AmfLibraryEntryIsSet = true;
}

bool AcesConfig::amfLibraryEntryIsSet() const
{
    return m_AmfLibraryEntryIsSet;
}

void AcesConfig::unsetAmfLibraryEntry()
{
    m_AmfLibraryEntryIsSet = false;
}



std::shared_ptr<OcioSource> AcesConfig::getOcioSource() const
{
    return m_OcioSource;
}

void AcesConfig::setOcioSource(const std::shared_ptr<OcioSource>& value)
{
	std::shared_ptr<OcioSource> v = value;
    m_OcioSource = v;
    m_OcioSourceIsSet = true;
}

bool AcesConfig::ocioSourceIsSet() const
{
    return m_OcioSourceIsSet;
}

void AcesConfig::unsetOcioSource()
{
    m_OcioSourceIsSet = false;
}


std::shared_ptr<OcioDisplayView> AcesConfig::getOcioDisplayView() const
{
    return m_OcioDisplayView;
}

void AcesConfig::setOcioDisplayView(const std::shared_ptr<OcioDisplayView>& value)
{
	std::shared_ptr<OcioDisplayView> v = value;
    m_OcioDisplayView = v;
    m_OcioDisplayViewIsSet = true;
}

bool AcesConfig::ocioDisplayViewIsSet() const
{
    return m_OcioDisplayViewIsSet;
}

void AcesConfig::unsetOcioDisplayView()
{
    m_OcioDisplayViewIsSet = false;
}


bool AcesConfig::isEnableArriWVOLogC4Decoder() const
{
    return m_EnableArriWVOLogC4Decoder;
}

void AcesConfig::setEnableArriWVOLogC4Decoder(bool value)
{
	bool v = value;
    m_EnableArriWVOLogC4Decoder = v;
    m_EnableArriWVOLogC4DecoderIsSet = true;
}

bool AcesConfig::enableArriWVOLogC4DecoderIsSet() const
{
    return m_EnableArriWVOLogC4DecoderIsSet;
}

void AcesConfig::unsetEnableArriWVOLogC4Decoder()
{
    m_EnableArriWVOLogC4DecoderIsSet = false;
}


}
}
}
}


