/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * AcesIdt.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AcesIdt_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AcesIdt_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  AcesIdt
    : public ModelBase
{
public:
    AcesIdt();
    virtual ~AcesIdt();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;
    bool applyMinMaxConstraints() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAcesIdt
    {
        AcesIdt_ARRI_LOGC3_EI800_,
        AcesIdt_ARRI_LOGC4,
        AcesIdt_CANONLOG2_CINEMAGAMUT_D55,
        AcesIdt_CANONLOG3_CINEMAGAMUT_D55,
        AcesIdt_V_LOG_V_GAMUT,
        AcesIdt_LOG3G10_REDWIDEGAMUTRGB,
        AcesIdt_S_LOG3_S_GAMUT3,
        AcesIdt_S_LOG3_S_GAMUT3_CINE,
        AcesIdt_S_LOG3_VENICE_S_GAMUT3,
        AcesIdt_S_LOG3_VENICE_S_GAMUT3_CINE,
        AcesIdt_NON_ACES_IDT,
    };

    eAcesIdt getValue() const;
    void setValue(eAcesIdt const value);

    protected:
        eAcesIdt m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AcesIdt_H_ */
