/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */



#include "ColorfrontTvMode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




ColorfrontTvMode::ColorfrontTvMode()
{
    m_EngineIsSet = false;
    m_InDynRangeGamutIsSet = false;
    m_OutDynRangeGamutIsSet = false;
    m_Brightness = 0.0;
    m_BrightnessIsSet = false;
    m_Highlight = 0.0;
    m_HighlightIsSet = false;
    m_Colorfulness = 0.0;
    m_ColorfulnessIsSet = false;
    m_SuperHighlight = 0.0;
    m_SuperHighlightIsSet = false;
    m_Roundtrip = false;
    m_RoundtripIsSet = false;
    m_ClampToLegal = false;
    m_ClampToLegalIsSet = false;
    m_ColorCorrector = false;
    m_ColorCorrectorIsSet = false;
    m_LiftMaster = 0.0;
    m_LiftMasterIsSet = false;
    m_LiftRed = 0.0;
    m_LiftRedIsSet = false;
    m_LiftGreen = 0.0;
    m_LiftGreenIsSet = false;
    m_LiftBlue = 0.0;
    m_LiftBlueIsSet = false;
    m_GammaMaster = 0.0;
    m_GammaMasterIsSet = false;
    m_GammaRed = 0.0;
    m_GammaRedIsSet = false;
    m_GammaGreen = 0.0;
    m_GammaGreenIsSet = false;
    m_GammaBlue = 0.0;
    m_GammaBlueIsSet = false;
    m_GainMaster = 0.0;
    m_GainMasterIsSet = false;
    m_GainRed = 0.0;
    m_GainRedIsSet = false;
    m_GainGreen = 0.0;
    m_GainGreenIsSet = false;
    m_GainBlue = 0.0;
    m_GainBlueIsSet = false;
    m_Saturation = 0.0;
    m_SaturationIsSet = false;
    m_CameraCorrection = false;
    m_CameraCorrectionIsSet = false;
    m_Exposure = 0.0;
    m_ExposureIsSet = false;
    m_ColorTemp = 0.0;
    m_ColorTempIsSet = false;
    m_Tint = 0.0;
    m_TintIsSet = false;
}

ColorfrontTvMode::~ColorfrontTvMode()
{
}

void ColorfrontTvMode::validate()
{
    // TODO: implement validation
}

bool ColorfrontTvMode::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	if (brightnessIsSet())
	{
		bool brightnessChanged = false;
		double v = getBrightness();
		double min = brightnessMin();
		double max = brightnessMax();
		if (v < min) { v = min; brightnessChanged = true; }
		if (v > max) { v = max; brightnessChanged = true; }
		if (brightnessChanged) { setBrightness(v); anyMinMaxValueChanged = true; }
	}
	if (highlightIsSet())
	{
		bool highlightChanged = false;
		double v = getHighlight();
		double min = highlightMin();
		double max = highlightMax();
		if (v < min) { v = min; highlightChanged = true; }
		if (v > max) { v = max; highlightChanged = true; }
		if (highlightChanged) { setHighlight(v); anyMinMaxValueChanged = true; }
	}
	if (colorfulnessIsSet())
	{
		bool colorfulnessChanged = false;
		double v = getColorfulness();
		double min = colorfulnessMin();
		double max = colorfulnessMax();
		if (v < min) { v = min; colorfulnessChanged = true; }
		if (v > max) { v = max; colorfulnessChanged = true; }
		if (colorfulnessChanged) { setColorfulness(v); anyMinMaxValueChanged = true; }
	}
	if (superHighlightIsSet())
	{
		bool superHighlightChanged = false;
		double v = getSuperHighlight();
		double min = superHighlightMin();
		double max = superHighlightMax();
		if (v < min) { v = min; superHighlightChanged = true; }
		if (v > max) { v = max; superHighlightChanged = true; }
		if (superHighlightChanged) { setSuperHighlight(v); anyMinMaxValueChanged = true; }
	}
	if (liftMasterIsSet())
	{
		bool liftMasterChanged = false;
		double v = getLiftMaster();
		double min = liftMasterMin();
		double max = liftMasterMax();
		if (v < min) { v = min; liftMasterChanged = true; }
		if (v > max) { v = max; liftMasterChanged = true; }
		if (liftMasterChanged) { setLiftMaster(v); anyMinMaxValueChanged = true; }
	}
	if (liftRedIsSet())
	{
		bool liftRedChanged = false;
		double v = getLiftRed();
		double min = liftRedMin();
		double max = liftRedMax();
		if (v < min) { v = min; liftRedChanged = true; }
		if (v > max) { v = max; liftRedChanged = true; }
		if (liftRedChanged) { setLiftRed(v); anyMinMaxValueChanged = true; }
	}
	if (liftGreenIsSet())
	{
		bool liftGreenChanged = false;
		double v = getLiftGreen();
		double min = liftGreenMin();
		double max = liftGreenMax();
		if (v < min) { v = min; liftGreenChanged = true; }
		if (v > max) { v = max; liftGreenChanged = true; }
		if (liftGreenChanged) { setLiftGreen(v); anyMinMaxValueChanged = true; }
	}
	if (liftBlueIsSet())
	{
		bool liftBlueChanged = false;
		double v = getLiftBlue();
		double min = liftBlueMin();
		double max = liftBlueMax();
		if (v < min) { v = min; liftBlueChanged = true; }
		if (v > max) { v = max; liftBlueChanged = true; }
		if (liftBlueChanged) { setLiftBlue(v); anyMinMaxValueChanged = true; }
	}
	if (gammaMasterIsSet())
	{
		bool gammaMasterChanged = false;
		double v = getGammaMaster();
		double min = gammaMasterMin();
		double max = gammaMasterMax();
		if (v < min) { v = min; gammaMasterChanged = true; }
		if (v > max) { v = max; gammaMasterChanged = true; }
		if (gammaMasterChanged) { setGammaMaster(v); anyMinMaxValueChanged = true; }
	}
	if (gammaRedIsSet())
	{
		bool gammaRedChanged = false;
		double v = getGammaRed();
		double min = gammaRedMin();
		double max = gammaRedMax();
		if (v < min) { v = min; gammaRedChanged = true; }
		if (v > max) { v = max; gammaRedChanged = true; }
		if (gammaRedChanged) { setGammaRed(v); anyMinMaxValueChanged = true; }
	}
	if (gammaGreenIsSet())
	{
		bool gammaGreenChanged = false;
		double v = getGammaGreen();
		double min = gammaGreenMin();
		double max = gammaGreenMax();
		if (v < min) { v = min; gammaGreenChanged = true; }
		if (v > max) { v = max; gammaGreenChanged = true; }
		if (gammaGreenChanged) { setGammaGreen(v); anyMinMaxValueChanged = true; }
	}
	if (gammaBlueIsSet())
	{
		bool gammaBlueChanged = false;
		double v = getGammaBlue();
		double min = gammaBlueMin();
		double max = gammaBlueMax();
		if (v < min) { v = min; gammaBlueChanged = true; }
		if (v > max) { v = max; gammaBlueChanged = true; }
		if (gammaBlueChanged) { setGammaBlue(v); anyMinMaxValueChanged = true; }
	}
	if (gainMasterIsSet())
	{
		bool gainMasterChanged = false;
		double v = getGainMaster();
		double min = gainMasterMin();
		double max = gainMasterMax();
		if (v < min) { v = min; gainMasterChanged = true; }
		if (v > max) { v = max; gainMasterChanged = true; }
		if (gainMasterChanged) { setGainMaster(v); anyMinMaxValueChanged = true; }
	}
	if (gainRedIsSet())
	{
		bool gainRedChanged = false;
		double v = getGainRed();
		double min = gainRedMin();
		double max = gainRedMax();
		if (v < min) { v = min; gainRedChanged = true; }
		if (v > max) { v = max; gainRedChanged = true; }
		if (gainRedChanged) { setGainRed(v); anyMinMaxValueChanged = true; }
	}
	if (gainGreenIsSet())
	{
		bool gainGreenChanged = false;
		double v = getGainGreen();
		double min = gainGreenMin();
		double max = gainGreenMax();
		if (v < min) { v = min; gainGreenChanged = true; }
		if (v > max) { v = max; gainGreenChanged = true; }
		if (gainGreenChanged) { setGainGreen(v); anyMinMaxValueChanged = true; }
	}
	if (gainBlueIsSet())
	{
		bool gainBlueChanged = false;
		double v = getGainBlue();
		double min = gainBlueMin();
		double max = gainBlueMax();
		if (v < min) { v = min; gainBlueChanged = true; }
		if (v > max) { v = max; gainBlueChanged = true; }
		if (gainBlueChanged) { setGainBlue(v); anyMinMaxValueChanged = true; }
	}
	if (saturationIsSet())
	{
		bool saturationChanged = false;
		double v = getSaturation();
		double min = saturationMin();
		double max = saturationMax();
		if (v < min) { v = min; saturationChanged = true; }
		if (v > max) { v = max; saturationChanged = true; }
		if (saturationChanged) { setSaturation(v); anyMinMaxValueChanged = true; }
	}
	if (exposureIsSet())
	{
		bool exposureChanged = false;
		double v = getExposure();
		double min = exposureMin();
		double max = exposureMax();
		if (v < min) { v = min; exposureChanged = true; }
		if (v > max) { v = max; exposureChanged = true; }
		if (exposureChanged) { setExposure(v); anyMinMaxValueChanged = true; }
	}
	if (colorTempIsSet())
	{
		bool colorTempChanged = false;
		double v = getColorTemp();
		double min = colorTempMin();
		double max = colorTempMax();
		if (v < min) { v = min; colorTempChanged = true; }
		if (v > max) { v = max; colorTempChanged = true; }
		if (colorTempChanged) { setColorTemp(v); anyMinMaxValueChanged = true; }
	}
	if (tintIsSet())
	{
		bool tintChanged = false;
		double v = getTint();
		double min = tintMin();
		double max = tintMax();
		if (v < min) { v = min; tintChanged = true; }
		if (v > max) { v = max; tintChanged = true; }
		if (tintChanged) { setTint(v); anyMinMaxValueChanged = true; }
	}
	return anyMinMaxValueChanged;
}

web::json::value ColorfrontTvMode::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EngineIsSet)
    {
        val[utility::conversions::to_string_t(U("engine"))] = ModelBase::toJson(m_Engine);
    }
    if(m_InDynRangeGamutIsSet)
    {
        val[utility::conversions::to_string_t(U("inDynRangeGamut"))] = ModelBase::toJson(m_InDynRangeGamut);
    }
    if(m_OutDynRangeGamutIsSet)
    {
        val[utility::conversions::to_string_t(U("outDynRangeGamut"))] = ModelBase::toJson(m_OutDynRangeGamut);
    }
    if(m_BrightnessIsSet)
    {
        val[utility::conversions::to_string_t(U("brightness"))] = ModelBase::toJson(m_Brightness);
    }
    if(m_HighlightIsSet)
    {
        val[utility::conversions::to_string_t(U("highlight"))] = ModelBase::toJson(m_Highlight);
    }
    if(m_ColorfulnessIsSet)
    {
        val[utility::conversions::to_string_t(U("colorfulness"))] = ModelBase::toJson(m_Colorfulness);
    }
    if(m_SuperHighlightIsSet)
    {
        val[utility::conversions::to_string_t(U("superHighlight"))] = ModelBase::toJson(m_SuperHighlight);
    }
    if(m_RoundtripIsSet)
    {
        val[utility::conversions::to_string_t(U("roundtrip"))] = ModelBase::toJson(m_Roundtrip);
    }
    if(m_ClampToLegalIsSet)
    {
        val[utility::conversions::to_string_t(U("clampToLegal"))] = ModelBase::toJson(m_ClampToLegal);
    }
    if(m_ColorCorrectorIsSet)
    {
        val[utility::conversions::to_string_t(U("colorCorrector"))] = ModelBase::toJson(m_ColorCorrector);
    }
    if(m_LiftMasterIsSet)
    {
        val[utility::conversions::to_string_t(U("liftMaster"))] = ModelBase::toJson(m_LiftMaster);
    }
    if(m_LiftRedIsSet)
    {
        val[utility::conversions::to_string_t(U("liftRed"))] = ModelBase::toJson(m_LiftRed);
    }
    if(m_LiftGreenIsSet)
    {
        val[utility::conversions::to_string_t(U("liftGreen"))] = ModelBase::toJson(m_LiftGreen);
    }
    if(m_LiftBlueIsSet)
    {
        val[utility::conversions::to_string_t(U("liftBlue"))] = ModelBase::toJson(m_LiftBlue);
    }
    if(m_GammaMasterIsSet)
    {
        val[utility::conversions::to_string_t(U("gammaMaster"))] = ModelBase::toJson(m_GammaMaster);
    }
    if(m_GammaRedIsSet)
    {
        val[utility::conversions::to_string_t(U("gammaRed"))] = ModelBase::toJson(m_GammaRed);
    }
    if(m_GammaGreenIsSet)
    {
        val[utility::conversions::to_string_t(U("gammaGreen"))] = ModelBase::toJson(m_GammaGreen);
    }
    if(m_GammaBlueIsSet)
    {
        val[utility::conversions::to_string_t(U("gammaBlue"))] = ModelBase::toJson(m_GammaBlue);
    }
    if(m_GainMasterIsSet)
    {
        val[utility::conversions::to_string_t(U("gainMaster"))] = ModelBase::toJson(m_GainMaster);
    }
    if(m_GainRedIsSet)
    {
        val[utility::conversions::to_string_t(U("gainRed"))] = ModelBase::toJson(m_GainRed);
    }
    if(m_GainGreenIsSet)
    {
        val[utility::conversions::to_string_t(U("gainGreen"))] = ModelBase::toJson(m_GainGreen);
    }
    if(m_GainBlueIsSet)
    {
        val[utility::conversions::to_string_t(U("gainBlue"))] = ModelBase::toJson(m_GainBlue);
    }
    if(m_SaturationIsSet)
    {
        val[utility::conversions::to_string_t(U("saturation"))] = ModelBase::toJson(m_Saturation);
    }
    if(m_CameraCorrectionIsSet)
    {
        val[utility::conversions::to_string_t(U("cameraCorrection"))] = ModelBase::toJson(m_CameraCorrection);
    }
    if(m_ExposureIsSet)
    {
        val[utility::conversions::to_string_t(U("exposure"))] = ModelBase::toJson(m_Exposure);
    }
    if(m_ColorTempIsSet)
    {
        val[utility::conversions::to_string_t(U("colorTemp"))] = ModelBase::toJson(m_ColorTemp);
    }
    if(m_TintIsSet)
    {
        val[utility::conversions::to_string_t(U("tint"))] = ModelBase::toJson(m_Tint);
    }

    return val;
}

bool ColorfrontTvMode::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("engine"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("engine")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ColorfrontEngine> refVal_engine;
            ok &= ModelBase::fromJson(fieldValue, refVal_engine);
            setEngine(refVal_engine);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("inDynRangeGamut"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("inDynRangeGamut")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ColorfrontDynRangeGamutTvModeIn> refVal_inDynRangeGamut;
            ok &= ModelBase::fromJson(fieldValue, refVal_inDynRangeGamut);
            setInDynRangeGamut(refVal_inDynRangeGamut);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("outDynRangeGamut"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("outDynRangeGamut")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ColorfrontDynRangeGamutTvModeOut> refVal_outDynRangeGamut;
            ok &= ModelBase::fromJson(fieldValue, refVal_outDynRangeGamut);
            setOutDynRangeGamut(refVal_outDynRangeGamut);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("brightness"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("brightness")));
        if(!fieldValue.is_null())
        {
            double refVal_brightness;
            ok &= ModelBase::fromJson(fieldValue, refVal_brightness);
            setBrightness(refVal_brightness);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("highlight"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("highlight")));
        if(!fieldValue.is_null())
        {
            double refVal_highlight;
            ok &= ModelBase::fromJson(fieldValue, refVal_highlight);
            setHighlight(refVal_highlight);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("colorfulness"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("colorfulness")));
        if(!fieldValue.is_null())
        {
            double refVal_colorfulness;
            ok &= ModelBase::fromJson(fieldValue, refVal_colorfulness);
            setColorfulness(refVal_colorfulness);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("superHighlight"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("superHighlight")));
        if(!fieldValue.is_null())
        {
            double refVal_superHighlight;
            ok &= ModelBase::fromJson(fieldValue, refVal_superHighlight);
            setSuperHighlight(refVal_superHighlight);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("roundtrip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("roundtrip")));
        if(!fieldValue.is_null())
        {
            bool refVal_roundtrip;
            ok &= ModelBase::fromJson(fieldValue, refVal_roundtrip);
            setRoundtrip(refVal_roundtrip);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("clampToLegal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("clampToLegal")));
        if(!fieldValue.is_null())
        {
            bool refVal_clampToLegal;
            ok &= ModelBase::fromJson(fieldValue, refVal_clampToLegal);
            setClampToLegal(refVal_clampToLegal);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("colorCorrector"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("colorCorrector")));
        if(!fieldValue.is_null())
        {
            bool refVal_colorCorrector;
            ok &= ModelBase::fromJson(fieldValue, refVal_colorCorrector);
            setColorCorrector(refVal_colorCorrector);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("liftMaster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("liftMaster")));
        if(!fieldValue.is_null())
        {
            double refVal_liftMaster;
            ok &= ModelBase::fromJson(fieldValue, refVal_liftMaster);
            setLiftMaster(refVal_liftMaster);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("liftRed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("liftRed")));
        if(!fieldValue.is_null())
        {
            double refVal_liftRed;
            ok &= ModelBase::fromJson(fieldValue, refVal_liftRed);
            setLiftRed(refVal_liftRed);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("liftGreen"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("liftGreen")));
        if(!fieldValue.is_null())
        {
            double refVal_liftGreen;
            ok &= ModelBase::fromJson(fieldValue, refVal_liftGreen);
            setLiftGreen(refVal_liftGreen);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("liftBlue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("liftBlue")));
        if(!fieldValue.is_null())
        {
            double refVal_liftBlue;
            ok &= ModelBase::fromJson(fieldValue, refVal_liftBlue);
            setLiftBlue(refVal_liftBlue);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gammaMaster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gammaMaster")));
        if(!fieldValue.is_null())
        {
            double refVal_gammaMaster;
            ok &= ModelBase::fromJson(fieldValue, refVal_gammaMaster);
            setGammaMaster(refVal_gammaMaster);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gammaRed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gammaRed")));
        if(!fieldValue.is_null())
        {
            double refVal_gammaRed;
            ok &= ModelBase::fromJson(fieldValue, refVal_gammaRed);
            setGammaRed(refVal_gammaRed);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gammaGreen"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gammaGreen")));
        if(!fieldValue.is_null())
        {
            double refVal_gammaGreen;
            ok &= ModelBase::fromJson(fieldValue, refVal_gammaGreen);
            setGammaGreen(refVal_gammaGreen);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gammaBlue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gammaBlue")));
        if(!fieldValue.is_null())
        {
            double refVal_gammaBlue;
            ok &= ModelBase::fromJson(fieldValue, refVal_gammaBlue);
            setGammaBlue(refVal_gammaBlue);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gainMaster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gainMaster")));
        if(!fieldValue.is_null())
        {
            double refVal_gainMaster;
            ok &= ModelBase::fromJson(fieldValue, refVal_gainMaster);
            setGainMaster(refVal_gainMaster);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gainRed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gainRed")));
        if(!fieldValue.is_null())
        {
            double refVal_gainRed;
            ok &= ModelBase::fromJson(fieldValue, refVal_gainRed);
            setGainRed(refVal_gainRed);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gainGreen"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gainGreen")));
        if(!fieldValue.is_null())
        {
            double refVal_gainGreen;
            ok &= ModelBase::fromJson(fieldValue, refVal_gainGreen);
            setGainGreen(refVal_gainGreen);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gainBlue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gainBlue")));
        if(!fieldValue.is_null())
        {
            double refVal_gainBlue;
            ok &= ModelBase::fromJson(fieldValue, refVal_gainBlue);
            setGainBlue(refVal_gainBlue);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("saturation"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("saturation")));
        if(!fieldValue.is_null())
        {
            double refVal_saturation;
            ok &= ModelBase::fromJson(fieldValue, refVal_saturation);
            setSaturation(refVal_saturation);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("cameraCorrection"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("cameraCorrection")));
        if(!fieldValue.is_null())
        {
            bool refVal_cameraCorrection;
            ok &= ModelBase::fromJson(fieldValue, refVal_cameraCorrection);
            setCameraCorrection(refVal_cameraCorrection);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("exposure"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("exposure")));
        if(!fieldValue.is_null())
        {
            double refVal_exposure;
            ok &= ModelBase::fromJson(fieldValue, refVal_exposure);
            setExposure(refVal_exposure);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("colorTemp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("colorTemp")));
        if(!fieldValue.is_null())
        {
            double refVal_colorTemp;
            ok &= ModelBase::fromJson(fieldValue, refVal_colorTemp);
            setColorTemp(refVal_colorTemp);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tint"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tint")));
        if(!fieldValue.is_null())
        {
            double refVal_tint;
            ok &= ModelBase::fromJson(fieldValue, refVal_tint);
            setTint(refVal_tint);
        }
    }
    
    applyMinMaxConstraints();
    return ok;
}

void ColorfrontTvMode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_EngineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("engine")), m_Engine));
    }
    if(m_InDynRangeGamutIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("inDynRangeGamut")), m_InDynRangeGamut));
    }
    if(m_OutDynRangeGamutIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("outDynRangeGamut")), m_OutDynRangeGamut));
    }
    if(m_BrightnessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("brightness")), m_Brightness));
    }
    if(m_HighlightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("highlight")), m_Highlight));
    }
    if(m_ColorfulnessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("colorfulness")), m_Colorfulness));
    }
    if(m_SuperHighlightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("superHighlight")), m_SuperHighlight));
    }
    if(m_RoundtripIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("roundtrip")), m_Roundtrip));
    }
    if(m_ClampToLegalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("clampToLegal")), m_ClampToLegal));
    }
    if(m_ColorCorrectorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("colorCorrector")), m_ColorCorrector));
    }
    if(m_LiftMasterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("liftMaster")), m_LiftMaster));
    }
    if(m_LiftRedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("liftRed")), m_LiftRed));
    }
    if(m_LiftGreenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("liftGreen")), m_LiftGreen));
    }
    if(m_LiftBlueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("liftBlue")), m_LiftBlue));
    }
    if(m_GammaMasterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gammaMaster")), m_GammaMaster));
    }
    if(m_GammaRedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gammaRed")), m_GammaRed));
    }
    if(m_GammaGreenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gammaGreen")), m_GammaGreen));
    }
    if(m_GammaBlueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gammaBlue")), m_GammaBlue));
    }
    if(m_GainMasterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gainMaster")), m_GainMaster));
    }
    if(m_GainRedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gainRed")), m_GainRed));
    }
    if(m_GainGreenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gainGreen")), m_GainGreen));
    }
    if(m_GainBlueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gainBlue")), m_GainBlue));
    }
    if(m_SaturationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("saturation")), m_Saturation));
    }
    if(m_CameraCorrectionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("cameraCorrection")), m_CameraCorrection));
    }
    if(m_ExposureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("exposure")), m_Exposure));
    }
    if(m_ColorTempIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("colorTemp")), m_ColorTemp));
    }
    if(m_TintIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tint")), m_Tint));
    }
}

bool ColorfrontTvMode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("engine"))))
    {
        std::shared_ptr<ColorfrontEngine> refVal_engine;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("engine"))), refVal_engine );
        setEngine(refVal_engine);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("inDynRangeGamut"))))
    {
        std::shared_ptr<ColorfrontDynRangeGamutTvModeIn> refVal_inDynRangeGamut;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("inDynRangeGamut"))), refVal_inDynRangeGamut );
        setInDynRangeGamut(refVal_inDynRangeGamut);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("outDynRangeGamut"))))
    {
        std::shared_ptr<ColorfrontDynRangeGamutTvModeOut> refVal_outDynRangeGamut;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("outDynRangeGamut"))), refVal_outDynRangeGamut );
        setOutDynRangeGamut(refVal_outDynRangeGamut);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("brightness"))))
    {
        double refVal_brightness;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("brightness"))), refVal_brightness );
        setBrightness(refVal_brightness);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("highlight"))))
    {
        double refVal_highlight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("highlight"))), refVal_highlight );
        setHighlight(refVal_highlight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("colorfulness"))))
    {
        double refVal_colorfulness;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("colorfulness"))), refVal_colorfulness );
        setColorfulness(refVal_colorfulness);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("superHighlight"))))
    {
        double refVal_superHighlight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("superHighlight"))), refVal_superHighlight );
        setSuperHighlight(refVal_superHighlight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("roundtrip"))))
    {
        bool refVal_roundtrip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("roundtrip"))), refVal_roundtrip );
        setRoundtrip(refVal_roundtrip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("clampToLegal"))))
    {
        bool refVal_clampToLegal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("clampToLegal"))), refVal_clampToLegal );
        setClampToLegal(refVal_clampToLegal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("colorCorrector"))))
    {
        bool refVal_colorCorrector;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("colorCorrector"))), refVal_colorCorrector );
        setColorCorrector(refVal_colorCorrector);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("liftMaster"))))
    {
        double refVal_liftMaster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("liftMaster"))), refVal_liftMaster );
        setLiftMaster(refVal_liftMaster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("liftRed"))))
    {
        double refVal_liftRed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("liftRed"))), refVal_liftRed );
        setLiftRed(refVal_liftRed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("liftGreen"))))
    {
        double refVal_liftGreen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("liftGreen"))), refVal_liftGreen );
        setLiftGreen(refVal_liftGreen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("liftBlue"))))
    {
        double refVal_liftBlue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("liftBlue"))), refVal_liftBlue );
        setLiftBlue(refVal_liftBlue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gammaMaster"))))
    {
        double refVal_gammaMaster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gammaMaster"))), refVal_gammaMaster );
        setGammaMaster(refVal_gammaMaster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gammaRed"))))
    {
        double refVal_gammaRed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gammaRed"))), refVal_gammaRed );
        setGammaRed(refVal_gammaRed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gammaGreen"))))
    {
        double refVal_gammaGreen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gammaGreen"))), refVal_gammaGreen );
        setGammaGreen(refVal_gammaGreen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gammaBlue"))))
    {
        double refVal_gammaBlue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gammaBlue"))), refVal_gammaBlue );
        setGammaBlue(refVal_gammaBlue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gainMaster"))))
    {
        double refVal_gainMaster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gainMaster"))), refVal_gainMaster );
        setGainMaster(refVal_gainMaster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gainRed"))))
    {
        double refVal_gainRed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gainRed"))), refVal_gainRed );
        setGainRed(refVal_gainRed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gainGreen"))))
    {
        double refVal_gainGreen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gainGreen"))), refVal_gainGreen );
        setGainGreen(refVal_gainGreen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gainBlue"))))
    {
        double refVal_gainBlue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gainBlue"))), refVal_gainBlue );
        setGainBlue(refVal_gainBlue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("saturation"))))
    {
        double refVal_saturation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("saturation"))), refVal_saturation );
        setSaturation(refVal_saturation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("cameraCorrection"))))
    {
        bool refVal_cameraCorrection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("cameraCorrection"))), refVal_cameraCorrection );
        setCameraCorrection(refVal_cameraCorrection);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("exposure"))))
    {
        double refVal_exposure;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("exposure"))), refVal_exposure );
        setExposure(refVal_exposure);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("colorTemp"))))
    {
        double refVal_colorTemp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("colorTemp"))), refVal_colorTemp );
        setColorTemp(refVal_colorTemp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tint"))))
    {
        double refVal_tint;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tint"))), refVal_tint );
        setTint(refVal_tint);
    }
    
    applyMinMaxConstraints();
    return ok;
}

std::shared_ptr<ColorfrontEngine> ColorfrontTvMode::getEngine() const
{
    return m_Engine;
}

void ColorfrontTvMode::setEngine(const std::shared_ptr<ColorfrontEngine>& value)
{
	std::shared_ptr<ColorfrontEngine> v = value;
    m_Engine = v;
    m_EngineIsSet = true;
}

bool ColorfrontTvMode::engineIsSet() const
{
    return m_EngineIsSet;
}

void ColorfrontTvMode::unsetEngine()
{
    m_EngineIsSet = false;
}


std::shared_ptr<ColorfrontDynRangeGamutTvModeIn> ColorfrontTvMode::getInDynRangeGamut() const
{
    return m_InDynRangeGamut;
}

void ColorfrontTvMode::setInDynRangeGamut(const std::shared_ptr<ColorfrontDynRangeGamutTvModeIn>& value)
{
	std::shared_ptr<ColorfrontDynRangeGamutTvModeIn> v = value;
    m_InDynRangeGamut = v;
    m_InDynRangeGamutIsSet = true;
}

bool ColorfrontTvMode::inDynRangeGamutIsSet() const
{
    return m_InDynRangeGamutIsSet;
}

void ColorfrontTvMode::unsetInDynRangeGamut()
{
    m_InDynRangeGamutIsSet = false;
}


std::shared_ptr<ColorfrontDynRangeGamutTvModeOut> ColorfrontTvMode::getOutDynRangeGamut() const
{
    return m_OutDynRangeGamut;
}

void ColorfrontTvMode::setOutDynRangeGamut(const std::shared_ptr<ColorfrontDynRangeGamutTvModeOut>& value)
{
	std::shared_ptr<ColorfrontDynRangeGamutTvModeOut> v = value;
    m_OutDynRangeGamut = v;
    m_OutDynRangeGamutIsSet = true;
}

bool ColorfrontTvMode::outDynRangeGamutIsSet() const
{
    return m_OutDynRangeGamutIsSet;
}

void ColorfrontTvMode::unsetOutDynRangeGamut()
{
    m_OutDynRangeGamutIsSet = false;
}


double ColorfrontTvMode::getBrightness() const
{
    return m_Brightness;
}

void ColorfrontTvMode::setBrightness(double value)
{
	double v = value;
	double min = brightnessMin();
	double max = brightnessMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Brightness = v;
    m_BrightnessIsSet = true;
}

bool ColorfrontTvMode::brightnessIsSet() const
{
    return m_BrightnessIsSet;
}

void ColorfrontTvMode::unsetBrightness()
{
    m_BrightnessIsSet = false;
}

double ColorfrontTvMode::brightnessMin() const {
	return -1.0;
}

double ColorfrontTvMode::brightnessMax() const {
	return 1.0;
}

double ColorfrontTvMode::getHighlight() const
{
    return m_Highlight;
}

void ColorfrontTvMode::setHighlight(double value)
{
	double v = value;
	double min = highlightMin();
	double max = highlightMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Highlight = v;
    m_HighlightIsSet = true;
}

bool ColorfrontTvMode::highlightIsSet() const
{
    return m_HighlightIsSet;
}

void ColorfrontTvMode::unsetHighlight()
{
    m_HighlightIsSet = false;
}

double ColorfrontTvMode::highlightMin() const {
	return -1.0;
}

double ColorfrontTvMode::highlightMax() const {
	return 1.0;
}

double ColorfrontTvMode::getColorfulness() const
{
    return m_Colorfulness;
}

void ColorfrontTvMode::setColorfulness(double value)
{
	double v = value;
	double min = colorfulnessMin();
	double max = colorfulnessMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Colorfulness = v;
    m_ColorfulnessIsSet = true;
}

bool ColorfrontTvMode::colorfulnessIsSet() const
{
    return m_ColorfulnessIsSet;
}

void ColorfrontTvMode::unsetColorfulness()
{
    m_ColorfulnessIsSet = false;
}

double ColorfrontTvMode::colorfulnessMin() const {
	return -1.0;
}

double ColorfrontTvMode::colorfulnessMax() const {
	return 1.0;
}

double ColorfrontTvMode::getSuperHighlight() const
{
    return m_SuperHighlight;
}

void ColorfrontTvMode::setSuperHighlight(double value)
{
	double v = value;
	double min = superHighlightMin();
	double max = superHighlightMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_SuperHighlight = v;
    m_SuperHighlightIsSet = true;
}

bool ColorfrontTvMode::superHighlightIsSet() const
{
    return m_SuperHighlightIsSet;
}

void ColorfrontTvMode::unsetSuperHighlight()
{
    m_SuperHighlightIsSet = false;
}

double ColorfrontTvMode::superHighlightMin() const {
	return -1.0;
}

double ColorfrontTvMode::superHighlightMax() const {
	return 1.0;
}

bool ColorfrontTvMode::isRoundtrip() const
{
    return m_Roundtrip;
}

void ColorfrontTvMode::setRoundtrip(bool value)
{
	bool v = value;
    m_Roundtrip = v;
    m_RoundtripIsSet = true;
}

bool ColorfrontTvMode::roundtripIsSet() const
{
    return m_RoundtripIsSet;
}

void ColorfrontTvMode::unsetRoundtrip()
{
    m_RoundtripIsSet = false;
}


bool ColorfrontTvMode::isClampToLegal() const
{
    return m_ClampToLegal;
}

void ColorfrontTvMode::setClampToLegal(bool value)
{
	bool v = value;
    m_ClampToLegal = v;
    m_ClampToLegalIsSet = true;
}

bool ColorfrontTvMode::clampToLegalIsSet() const
{
    return m_ClampToLegalIsSet;
}

void ColorfrontTvMode::unsetClampToLegal()
{
    m_ClampToLegalIsSet = false;
}


bool ColorfrontTvMode::isColorCorrector() const
{
    return m_ColorCorrector;
}

void ColorfrontTvMode::setColorCorrector(bool value)
{
	bool v = value;
    m_ColorCorrector = v;
    m_ColorCorrectorIsSet = true;
}

bool ColorfrontTvMode::colorCorrectorIsSet() const
{
    return m_ColorCorrectorIsSet;
}

void ColorfrontTvMode::unsetColorCorrector()
{
    m_ColorCorrectorIsSet = false;
}


double ColorfrontTvMode::getLiftMaster() const
{
    return m_LiftMaster;
}

void ColorfrontTvMode::setLiftMaster(double value)
{
	double v = value;
	double min = liftMasterMin();
	double max = liftMasterMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_LiftMaster = v;
    m_LiftMasterIsSet = true;
}

bool ColorfrontTvMode::liftMasterIsSet() const
{
    return m_LiftMasterIsSet;
}

void ColorfrontTvMode::unsetLiftMaster()
{
    m_LiftMasterIsSet = false;
}

double ColorfrontTvMode::liftMasterMin() const {
	return -1.0;
}

double ColorfrontTvMode::liftMasterMax() const {
	return 1.0;
}

double ColorfrontTvMode::getLiftRed() const
{
    return m_LiftRed;
}

void ColorfrontTvMode::setLiftRed(double value)
{
	double v = value;
	double min = liftRedMin();
	double max = liftRedMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_LiftRed = v;
    m_LiftRedIsSet = true;
}

bool ColorfrontTvMode::liftRedIsSet() const
{
    return m_LiftRedIsSet;
}

void ColorfrontTvMode::unsetLiftRed()
{
    m_LiftRedIsSet = false;
}

double ColorfrontTvMode::liftRedMin() const {
	return -1.0;
}

double ColorfrontTvMode::liftRedMax() const {
	return 1.0;
}

double ColorfrontTvMode::getLiftGreen() const
{
    return m_LiftGreen;
}

void ColorfrontTvMode::setLiftGreen(double value)
{
	double v = value;
	double min = liftGreenMin();
	double max = liftGreenMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_LiftGreen = v;
    m_LiftGreenIsSet = true;
}

bool ColorfrontTvMode::liftGreenIsSet() const
{
    return m_LiftGreenIsSet;
}

void ColorfrontTvMode::unsetLiftGreen()
{
    m_LiftGreenIsSet = false;
}

double ColorfrontTvMode::liftGreenMin() const {
	return -1.0;
}

double ColorfrontTvMode::liftGreenMax() const {
	return 1.0;
}

double ColorfrontTvMode::getLiftBlue() const
{
    return m_LiftBlue;
}

void ColorfrontTvMode::setLiftBlue(double value)
{
	double v = value;
	double min = liftBlueMin();
	double max = liftBlueMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_LiftBlue = v;
    m_LiftBlueIsSet = true;
}

bool ColorfrontTvMode::liftBlueIsSet() const
{
    return m_LiftBlueIsSet;
}

void ColorfrontTvMode::unsetLiftBlue()
{
    m_LiftBlueIsSet = false;
}

double ColorfrontTvMode::liftBlueMin() const {
	return -1.0;
}

double ColorfrontTvMode::liftBlueMax() const {
	return 1.0;
}

double ColorfrontTvMode::getGammaMaster() const
{
    return m_GammaMaster;
}

void ColorfrontTvMode::setGammaMaster(double value)
{
	double v = value;
	double min = gammaMasterMin();
	double max = gammaMasterMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GammaMaster = v;
    m_GammaMasterIsSet = true;
}

bool ColorfrontTvMode::gammaMasterIsSet() const
{
    return m_GammaMasterIsSet;
}

void ColorfrontTvMode::unsetGammaMaster()
{
    m_GammaMasterIsSet = false;
}

double ColorfrontTvMode::gammaMasterMin() const {
	return 0.0;
}

double ColorfrontTvMode::gammaMasterMax() const {
	return 2.0;
}

double ColorfrontTvMode::getGammaRed() const
{
    return m_GammaRed;
}

void ColorfrontTvMode::setGammaRed(double value)
{
	double v = value;
	double min = gammaRedMin();
	double max = gammaRedMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GammaRed = v;
    m_GammaRedIsSet = true;
}

bool ColorfrontTvMode::gammaRedIsSet() const
{
    return m_GammaRedIsSet;
}

void ColorfrontTvMode::unsetGammaRed()
{
    m_GammaRedIsSet = false;
}

double ColorfrontTvMode::gammaRedMin() const {
	return 0.0;
}

double ColorfrontTvMode::gammaRedMax() const {
	return 2.0;
}

double ColorfrontTvMode::getGammaGreen() const
{
    return m_GammaGreen;
}

void ColorfrontTvMode::setGammaGreen(double value)
{
	double v = value;
	double min = gammaGreenMin();
	double max = gammaGreenMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GammaGreen = v;
    m_GammaGreenIsSet = true;
}

bool ColorfrontTvMode::gammaGreenIsSet() const
{
    return m_GammaGreenIsSet;
}

void ColorfrontTvMode::unsetGammaGreen()
{
    m_GammaGreenIsSet = false;
}

double ColorfrontTvMode::gammaGreenMin() const {
	return 0.0;
}

double ColorfrontTvMode::gammaGreenMax() const {
	return 2.0;
}

double ColorfrontTvMode::getGammaBlue() const
{
    return m_GammaBlue;
}

void ColorfrontTvMode::setGammaBlue(double value)
{
	double v = value;
	double min = gammaBlueMin();
	double max = gammaBlueMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GammaBlue = v;
    m_GammaBlueIsSet = true;
}

bool ColorfrontTvMode::gammaBlueIsSet() const
{
    return m_GammaBlueIsSet;
}

void ColorfrontTvMode::unsetGammaBlue()
{
    m_GammaBlueIsSet = false;
}

double ColorfrontTvMode::gammaBlueMin() const {
	return 0.0;
}

double ColorfrontTvMode::gammaBlueMax() const {
	return 2.0;
}

double ColorfrontTvMode::getGainMaster() const
{
    return m_GainMaster;
}

void ColorfrontTvMode::setGainMaster(double value)
{
	double v = value;
	double min = gainMasterMin();
	double max = gainMasterMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GainMaster = v;
    m_GainMasterIsSet = true;
}

bool ColorfrontTvMode::gainMasterIsSet() const
{
    return m_GainMasterIsSet;
}

void ColorfrontTvMode::unsetGainMaster()
{
    m_GainMasterIsSet = false;
}

double ColorfrontTvMode::gainMasterMin() const {
	return 0.0;
}

double ColorfrontTvMode::gainMasterMax() const {
	return 5.0;
}

double ColorfrontTvMode::getGainRed() const
{
    return m_GainRed;
}

void ColorfrontTvMode::setGainRed(double value)
{
	double v = value;
	double min = gainRedMin();
	double max = gainRedMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GainRed = v;
    m_GainRedIsSet = true;
}

bool ColorfrontTvMode::gainRedIsSet() const
{
    return m_GainRedIsSet;
}

void ColorfrontTvMode::unsetGainRed()
{
    m_GainRedIsSet = false;
}

double ColorfrontTvMode::gainRedMin() const {
	return 0.0;
}

double ColorfrontTvMode::gainRedMax() const {
	return 5.0;
}

double ColorfrontTvMode::getGainGreen() const
{
    return m_GainGreen;
}

void ColorfrontTvMode::setGainGreen(double value)
{
	double v = value;
	double min = gainGreenMin();
	double max = gainGreenMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GainGreen = v;
    m_GainGreenIsSet = true;
}

bool ColorfrontTvMode::gainGreenIsSet() const
{
    return m_GainGreenIsSet;
}

void ColorfrontTvMode::unsetGainGreen()
{
    m_GainGreenIsSet = false;
}

double ColorfrontTvMode::gainGreenMin() const {
	return 0.0;
}

double ColorfrontTvMode::gainGreenMax() const {
	return 5.0;
}

double ColorfrontTvMode::getGainBlue() const
{
    return m_GainBlue;
}

void ColorfrontTvMode::setGainBlue(double value)
{
	double v = value;
	double min = gainBlueMin();
	double max = gainBlueMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_GainBlue = v;
    m_GainBlueIsSet = true;
}

bool ColorfrontTvMode::gainBlueIsSet() const
{
    return m_GainBlueIsSet;
}

void ColorfrontTvMode::unsetGainBlue()
{
    m_GainBlueIsSet = false;
}

double ColorfrontTvMode::gainBlueMin() const {
	return 0.0;
}

double ColorfrontTvMode::gainBlueMax() const {
	return 5.0;
}

double ColorfrontTvMode::getSaturation() const
{
    return m_Saturation;
}

void ColorfrontTvMode::setSaturation(double value)
{
	double v = value;
	double min = saturationMin();
	double max = saturationMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Saturation = v;
    m_SaturationIsSet = true;
}

bool ColorfrontTvMode::saturationIsSet() const
{
    return m_SaturationIsSet;
}

void ColorfrontTvMode::unsetSaturation()
{
    m_SaturationIsSet = false;
}

double ColorfrontTvMode::saturationMin() const {
	return 0.0;
}

double ColorfrontTvMode::saturationMax() const {
	return 2.0;
}

bool ColorfrontTvMode::isCameraCorrection() const
{
    return m_CameraCorrection;
}

void ColorfrontTvMode::setCameraCorrection(bool value)
{
	bool v = value;
    m_CameraCorrection = v;
    m_CameraCorrectionIsSet = true;
}

bool ColorfrontTvMode::cameraCorrectionIsSet() const
{
    return m_CameraCorrectionIsSet;
}

void ColorfrontTvMode::unsetCameraCorrection()
{
    m_CameraCorrectionIsSet = false;
}


double ColorfrontTvMode::getExposure() const
{
    return m_Exposure;
}

void ColorfrontTvMode::setExposure(double value)
{
	double v = value;
	double min = exposureMin();
	double max = exposureMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Exposure = v;
    m_ExposureIsSet = true;
}

bool ColorfrontTvMode::exposureIsSet() const
{
    return m_ExposureIsSet;
}

void ColorfrontTvMode::unsetExposure()
{
    m_ExposureIsSet = false;
}

double ColorfrontTvMode::exposureMin() const {
	return -4.0;
}

double ColorfrontTvMode::exposureMax() const {
	return 4.0;
}

double ColorfrontTvMode::getColorTemp() const
{
    return m_ColorTemp;
}

void ColorfrontTvMode::setColorTemp(double value)
{
	double v = value;
	double min = colorTempMin();
	double max = colorTempMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_ColorTemp = v;
    m_ColorTempIsSet = true;
}

bool ColorfrontTvMode::colorTempIsSet() const
{
    return m_ColorTempIsSet;
}

void ColorfrontTvMode::unsetColorTemp()
{
    m_ColorTempIsSet = false;
}

double ColorfrontTvMode::colorTempMin() const {
	return -10.0;
}

double ColorfrontTvMode::colorTempMax() const {
	return 10.0;
}

double ColorfrontTvMode::getTint() const
{
    return m_Tint;
}

void ColorfrontTvMode::setTint(double value)
{
	double v = value;
	double min = tintMin();
	double max = tintMax();
	if (v < min) { v = min; }
	if (v > max) { v = max; }
    m_Tint = v;
    m_TintIsSet = true;
}

bool ColorfrontTvMode::tintIsSet() const
{
    return m_TintIsSet;
}

void ColorfrontTvMode::unsetTint()
{
    m_TintIsSet = false;
}

double ColorfrontTvMode::tintMin() const {
	return -16.0;
}

double ColorfrontTvMode::tintMax() const {
	return 16.0;
}

}
}
}
}


