/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */



#include "Mode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

Mode::eMode toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Input")))
        return Mode::eMode::Mode_INPUT;
    if (val == utility::conversions::to_string_t(U("Output")))
        return Mode::eMode::Mode_OUTPUT;
    return {};
}

EnumUnderlyingType fromEnum(Mode::eMode e)
{
    switch (e)
    {
    case Mode::eMode::Mode_INPUT:
        return U("Input");
    case Mode::eMode::Mode_OUTPUT:
        return U("Output");
    default:
        break;
    }
    return {};
}
}

Mode::Mode()
{
}

Mode::~Mode()
{
}

void Mode::validate()
{
    // TODO: implement validation
}

bool Mode::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

web::json::value Mode::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Mode::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Mode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Mode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Mode::eMode Mode::getValue() const
{
   return m_value;
}

void Mode::setValue(Mode::eMode const value)
{
   m_value = value;
}


}
}
}
}


