/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */



#include "OcioSource.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

OcioSource::eOcioSource toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("ARRI LogC3 (EI800)")))
        return OcioSource::eOcioSource::OcioSource_ARRI_LOGC3_EI800_;
    if (val == utility::conversions::to_string_t(U("ARRI LogC4")))
        return OcioSource::eOcioSource::OcioSource_ARRI_LOGC4;
    if (val == utility::conversions::to_string_t(U("BMDFilm WideGamut Gen5")))
        return OcioSource::eOcioSource::OcioSource_BMDFILM_WIDEGAMUT_GEN5;
    if (val == utility::conversions::to_string_t(U("CanonLog2 CinemaGamut D55")))
        return OcioSource::eOcioSource::OcioSource_CANONLOG2_CINEMAGAMUT_D55;
    if (val == utility::conversions::to_string_t(U("CanonLog3 CinemaGamut D55")))
        return OcioSource::eOcioSource::OcioSource_CANONLOG3_CINEMAGAMUT_D55;
    if (val == utility::conversions::to_string_t(U("V-Log V-Gamut")))
        return OcioSource::eOcioSource::OcioSource_V_LOG_V_GAMUT;
    if (val == utility::conversions::to_string_t(U("Log3G10 REDWideGamutRGB")))
        return OcioSource::eOcioSource::OcioSource_LOG3G10_REDWIDEGAMUTRGB;
    if (val == utility::conversions::to_string_t(U("S-Log3 S-Gamut3")))
        return OcioSource::eOcioSource::OcioSource_S_LOG3_S_GAMUT3;
    if (val == utility::conversions::to_string_t(U("S-Log3 S-Gamut3.Cine")))
        return OcioSource::eOcioSource::OcioSource_S_LOG3_S_GAMUT3_CINE;
    if (val == utility::conversions::to_string_t(U("S-Log3 Venice S-Gamut3")))
        return OcioSource::eOcioSource::OcioSource_S_LOG3_VENICE_S_GAMUT3;
    if (val == utility::conversions::to_string_t(U("S-Log3 Venice S-Gamut3.Cine")))
        return OcioSource::eOcioSource::OcioSource_S_LOG3_VENICE_S_GAMUT3_CINE;
    if (val == utility::conversions::to_string_t(U("Camera Rec.709")))
        return OcioSource::eOcioSource::OcioSource_CAMERA_REC_709;
    return {};
}

EnumUnderlyingType fromEnum(OcioSource::eOcioSource e)
{
    switch (e)
    {
    case OcioSource::eOcioSource::OcioSource_ARRI_LOGC3_EI800_:
        return U("ARRI LogC3 (EI800)");
    case OcioSource::eOcioSource::OcioSource_ARRI_LOGC4:
        return U("ARRI LogC4");
    case OcioSource::eOcioSource::OcioSource_BMDFILM_WIDEGAMUT_GEN5:
        return U("BMDFilm WideGamut Gen5");
    case OcioSource::eOcioSource::OcioSource_CANONLOG2_CINEMAGAMUT_D55:
        return U("CanonLog2 CinemaGamut D55");
    case OcioSource::eOcioSource::OcioSource_CANONLOG3_CINEMAGAMUT_D55:
        return U("CanonLog3 CinemaGamut D55");
    case OcioSource::eOcioSource::OcioSource_V_LOG_V_GAMUT:
        return U("V-Log V-Gamut");
    case OcioSource::eOcioSource::OcioSource_LOG3G10_REDWIDEGAMUTRGB:
        return U("Log3G10 REDWideGamutRGB");
    case OcioSource::eOcioSource::OcioSource_S_LOG3_S_GAMUT3:
        return U("S-Log3 S-Gamut3");
    case OcioSource::eOcioSource::OcioSource_S_LOG3_S_GAMUT3_CINE:
        return U("S-Log3 S-Gamut3.Cine");
    case OcioSource::eOcioSource::OcioSource_S_LOG3_VENICE_S_GAMUT3:
        return U("S-Log3 Venice S-Gamut3");
    case OcioSource::eOcioSource::OcioSource_S_LOG3_VENICE_S_GAMUT3_CINE:
        return U("S-Log3 Venice S-Gamut3.Cine");
    case OcioSource::eOcioSource::OcioSource_CAMERA_REC_709:
        return U("Camera Rec.709");
    default:
        break;
    }
    return {};
}
}

OcioSource::OcioSource()
{
}

OcioSource::~OcioSource()
{
}

void OcioSource::validate()
{
    // TODO: implement validation
}

bool OcioSource::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

web::json::value OcioSource::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool OcioSource::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void OcioSource::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool OcioSource::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

OcioSource::eOcioSource OcioSource::getValue() const
{
   return m_value;
}

void OcioSource::setValue(OcioSource::eOcioSource const value)
{
   m_value = value;
}


}
}
}
}


