/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */



#include "OrionMode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

OrionMode::eOrionMode toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Display Light")))
        return OrionMode::eOrionMode::OrionMode_DISPLAY_LIGHT;
    if (val == utility::conversions::to_string_t(U("Scene Light")))
        return OrionMode::eOrionMode::OrionMode_SCENE_LIGHT;
    return {};
}

EnumUnderlyingType fromEnum(OrionMode::eOrionMode e)
{
    switch (e)
    {
    case OrionMode::eOrionMode::OrionMode_DISPLAY_LIGHT:
        return U("Display Light");
    case OrionMode::eOrionMode::OrionMode_SCENE_LIGHT:
        return U("Scene Light");
    default:
        break;
    }
    return {};
}
}

OrionMode::OrionMode()
{
}

OrionMode::~OrionMode()
{
}

void OrionMode::validate()
{
    // TODO: implement validation
}

bool OrionMode::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

web::json::value OrionMode::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool OrionMode::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void OrionMode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool OrionMode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

OrionMode::eOrionMode OrionMode::getValue() const
{
   return m_value;
}

void OrionMode::setValue(OrionMode::eOrionMode const value)
{
   m_value = value;
}


}
}
}
}


