/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OutputConfig.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OutputConfig_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OutputConfig_H_


#include "ModelBase.h"

#include "model/SdiMode3g.h"
#include "model/VideoFormat.h"
#include "model/ColorSpace.h"
#include "model/RgbRange.h"
#include "model/Crop4k2k.h"
#include "model/Colorimetry.h"
#include "model/BitDepth.h"
#include "model/ScanMode.h"
#include "model/Connection.h"
#include "model/DownConvert.h"
#include "model/Transfer.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  OutputConfig
    : public ModelBase
{
public:
    OutputConfig();
    virtual ~OutputConfig();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;
    bool applyMinMaxConstraints() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// OutputConfig members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ColorSpace> getColorSpace() const;
    bool colorSpaceIsSet() const;
    void unsetColorSpace();

    void setColorSpace(const std::shared_ptr<ColorSpace>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<RgbRange> getRgbRange() const;
    bool rgbRangeIsSet() const;
    void unsetRgbRange();

    void setRgbRange(const std::shared_ptr<RgbRange>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BitDepth> getBitDepth() const;
    bool bitDepthIsSet() const;
    void unsetBitDepth();

    void setBitDepth(const std::shared_ptr<BitDepth>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ScanMode> getScanMode() const;
    bool scanModeIsSet() const;
    void unsetScanMode();

    void setScanMode(const std::shared_ptr<ScanMode>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Colorimetry> getColorimetry() const;
    bool colorimetryIsSet() const;
    void unsetColorimetry();

    void setColorimetry(const std::shared_ptr<Colorimetry>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Transfer> getTransfer() const;
    bool transferIsSet() const;
    void unsetTransfer();

    void setTransfer(const std::shared_ptr<Transfer>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VideoFormat> getFormat() const;
    bool formatIsSet() const;
    void unsetFormat();

    void setFormat(const std::shared_ptr<VideoFormat>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VideoFormat> getSdiFormat() const;
    bool sdiFormatIsSet() const;
    void unsetSdiFormat();

    void setSdiFormat(const std::shared_ptr<VideoFormat>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DownConvert> getSdiDownConvert() const;
    bool sdiDownConvertIsSet() const;
    void unsetSdiDownConvert();

    void setSdiDownConvert(const std::shared_ptr<DownConvert>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<SdiMode3g> getSdiMode3g() const;
    bool sdiMode3gIsSet() const;
    void unsetSdiMode3g();

    void setSdiMode3g(const std::shared_ptr<SdiMode3g>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VideoFormat> getHdmiFormat() const;
    bool hdmiFormatIsSet() const;
    void unsetHdmiFormat();

    void setHdmiFormat(const std::shared_ptr<VideoFormat>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Connection> getHdmiConnection() const;
    bool hdmiConnectionIsSet() const;
    void unsetHdmiConnection();

    void setHdmiConnection(const std::shared_ptr<Connection>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Crop4k2k> getHdmiCrop4k2k() const;
    bool hdmiCrop4k2kIsSet() const;
    void unsetHdmiCrop4k2k();

    void setHdmiCrop4k2k(const std::shared_ptr<Crop4k2k>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DownConvert> getHdmiDownConvert() const;
    bool hdmiDownConvertIsSet() const;
    void unsetHdmiDownConvert();

    void setHdmiDownConvert(const std::shared_ptr<DownConvert>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ColorSpace> getHdmiColorSpace() const;
    bool hdmiColorSpaceIsSet() const;
    void unsetHdmiColorSpace();

    void setHdmiColorSpace(const std::shared_ptr<ColorSpace>& value);


    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BitDepth> getHdmiBitDepth() const;
    bool hdmiBitDepthIsSet() const;
    void unsetHdmiBitDepth();

    void setHdmiBitDepth(const std::shared_ptr<BitDepth>& value);



protected:
    std::shared_ptr<ColorSpace> m_ColorSpace;
    bool m_ColorSpaceIsSet;
    std::shared_ptr<RgbRange> m_RgbRange;
    bool m_RgbRangeIsSet;
    std::shared_ptr<BitDepth> m_BitDepth;
    bool m_BitDepthIsSet;
    std::shared_ptr<ScanMode> m_ScanMode;
    bool m_ScanModeIsSet;
    std::shared_ptr<Colorimetry> m_Colorimetry;
    bool m_ColorimetryIsSet;
    std::shared_ptr<Transfer> m_Transfer;
    bool m_TransferIsSet;
    std::shared_ptr<VideoFormat> m_Format;
    bool m_FormatIsSet;
    std::shared_ptr<VideoFormat> m_SdiFormat;
    bool m_SdiFormatIsSet;
    std::shared_ptr<DownConvert> m_SdiDownConvert;
    bool m_SdiDownConvertIsSet;
    std::shared_ptr<SdiMode3g> m_SdiMode3g;
    bool m_SdiMode3gIsSet;
    std::shared_ptr<VideoFormat> m_HdmiFormat;
    bool m_HdmiFormatIsSet;
    std::shared_ptr<Connection> m_HdmiConnection;
    bool m_HdmiConnectionIsSet;
    std::shared_ptr<Crop4k2k> m_HdmiCrop4k2k;
    bool m_HdmiCrop4k2kIsSet;
    std::shared_ptr<DownConvert> m_HdmiDownConvert;
    bool m_HdmiDownConvertIsSet;
    std::shared_ptr<ColorSpace> m_HdmiColorSpace;
    bool m_HdmiColorSpaceIsSet;
    std::shared_ptr<BitDepth> m_HdmiBitDepth;
    bool m_HdmiBitDepthIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OutputConfig_H_ */
