/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */



#include "ScanMode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

ScanMode::eScanMode toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Auto")))
        return ScanMode::eScanMode::ScanMode_AUTO;
    if (val == utility::conversions::to_string_t(U("Progressive")))
        return ScanMode::eScanMode::ScanMode_PROGRESSIVE;
    if (val == utility::conversions::to_string_t(U("Interlaced")))
        return ScanMode::eScanMode::ScanMode_INTERLACED;
    if (val == utility::conversions::to_string_t(U("PsF")))
        return ScanMode::eScanMode::ScanMode_PSF;
    return {};
}

EnumUnderlyingType fromEnum(ScanMode::eScanMode e)
{
    switch (e)
    {
    case ScanMode::eScanMode::ScanMode_AUTO:
        return U("Auto");
    case ScanMode::eScanMode::ScanMode_PROGRESSIVE:
        return U("Progressive");
    case ScanMode::eScanMode::ScanMode_INTERLACED:
        return U("Interlaced");
    case ScanMode::eScanMode::ScanMode_PSF:
        return U("PsF");
    default:
        break;
    }
    return {};
}
}

ScanMode::ScanMode()
{
}

ScanMode::~ScanMode()
{
}

void ScanMode::validate()
{
    // TODO: implement validation
}

bool ScanMode::applyMinMaxConstraints()
{
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

web::json::value ScanMode::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ScanMode::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ScanMode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ScanMode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ScanMode::eScanMode ScanMode::getValue() const
{
   return m_value;
}

void ScanMode::setValue(ScanMode::eScanMode const value)
{
   m_value = value;
}


}
}
}
}


