/**
 * OpenAPI Soji
 * This is a REST API for the AJA Soji product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

/*
 * OAIColorfrontConfig.h
 *
 * 
 */

#ifndef OAIColorfrontConfig_H
#define OAIColorfrontConfig_H

#include <QJsonObject>

#include "OAIColorfrontColorspace.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIColorfrontConfig : public OAIObject {
public:
    OAIColorfrontConfig();
    OAIColorfrontConfig(QString json);
    ~OAIColorfrontConfig() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isEnabled() const;
    void setEnabled(const bool &enabled);
    bool is_enabled_Set() const;
    bool is_enabled_Valid() const;

    OAIColorfrontColorspace getInColorspace() const;
    void setInColorspace(const OAIColorfrontColorspace &in_colorspace);
    bool is_in_colorspace_Set() const;
    bool is_in_colorspace_Valid() const;

    OAIColorfrontColorspace getOutColorspace() const;
    void setOutColorspace(const OAIColorfrontColorspace &out_colorspace);
    bool is_out_colorspace_Set() const;
    bool is_out_colorspace_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    virtual bool applyMinMaxConstraints();
private:
    void initializeModel();

    bool enabled;
    bool m_enabled_isSet;
    bool m_enabled_isValid;

    OAIColorfrontColorspace in_colorspace;
    bool m_in_colorspace_isSet;
    bool m_in_colorspace_isValid;

    OAIColorfrontColorspace out_colorspace;
    bool m_out_colorspace_isSet;
    bool m_out_colorspace_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIColorfrontConfig)

#endif // OAIColorfrontConfig_H
