/**
 * OpenAPI Soji
 * This is a REST API for the AJA Soji product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

/*
 * OAIColorfrontColorspace.h
 *
 * 
 */

#ifndef OAIColorfrontColorspace_H
#define OAIColorfrontColorspace_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIColorfrontColorspace : public OAIEnum {
public:
    OAIColorfrontColorspace();
    OAIColorfrontColorspace(QString json);
    ~OAIColorfrontColorspace() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIColorfrontColorspace {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        BT709, 
        PQ_BT2020, 
        HLG_BT2020
    };
    OAIColorfrontColorspace::eOAIColorfrontColorspace getValue() const;
    void setValue(const OAIColorfrontColorspace::eOAIColorfrontColorspace& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

    virtual bool applyMinMaxConstraints();
private:
    void initializeModel();

    eOAIColorfrontColorspace m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIColorfrontColorspace)

#endif // OAIColorfrontColorspace_H
