/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

#include "OAIOrionImplementation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIOrionImplementation::OAIOrionImplementation(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIOrionImplementation::OAIOrionImplementation() {
    this->initializeModel();
}

OAIOrionImplementation::~OAIOrionImplementation() {}

void OAIOrionImplementation::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIOrionImplementation::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIOrionImplementation::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Engine", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOrionImplementation::ENGINE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Render", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOrionImplementation::RENDER;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIOrionImplementation::fromJsonValue(QJsonValue json) {
fromJson(json.toString());

    applyMinMaxConstraints();
}

QString OAIOrionImplementation::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIOrionImplementation::ENGINE:
            val = "Engine";
            break;
        case eOAIOrionImplementation::RENDER:
            val = "Render";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIOrionImplementation::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIOrionImplementation::eOAIOrionImplementation OAIOrionImplementation::getValue() const {
    return m_value;
}

void OAIOrionImplementation::setValue(const OAIOrionImplementation::eOAIOrionImplementation& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIOrionImplementation::isSet() const {
    
    return m_value_isSet;
}

bool OAIOrionImplementation::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

bool OAIOrionImplementation::applyMinMaxConstraints() {
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

} // namespace OpenAPI
