/*
OpenAPI ColorBox

This is a REST API for the AJA ColorBox product.

The version of the OpenAPI document: 1.0.0
Contact: support@aja.com

NOTE: This code is auto generated by OpenAPI Generator (https://openapi-generator.tech).
      Do not edit this code manually.

Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
*/

package openapi

import (
	"encoding/json"
)

// ColorfrontUpmapMode struct for ColorfrontUpmapMode
type ColorfrontUpmapMode struct {
	Bypass *bool `json:"bypass,omitempty"`
	Contrast *ColorfrontLowMidHigh `json:"contrast,omitempty"`
	Highlights *ColorfrontLowMidHigh `json:"highlights,omitempty"`
}

// NewColorfrontUpmapMode instantiates a new ColorfrontUpmapMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColorfrontUpmapMode() *ColorfrontUpmapMode {
	this := ColorfrontUpmapMode{}
	var bypass bool = false
	this.Bypass = &bypass
	var contrast ColorfrontLowMidHigh = COLORFRONTLOWMIDHIGH_MID
	this.Contrast = &contrast
	var highlights ColorfrontLowMidHigh = COLORFRONTLOWMIDHIGH_MID
	this.Highlights = &highlights
	return &this
}

// NewColorfrontUpmapModeWithDefaults instantiates a new ColorfrontUpmapMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColorfrontUpmapModeWithDefaults() *ColorfrontUpmapMode {
	this := ColorfrontUpmapMode{}
	var bypass bool = false
	this.Bypass = &bypass
	var contrast ColorfrontLowMidHigh = COLORFRONTLOWMIDHIGH_MID
	this.Contrast = &contrast
	var highlights ColorfrontLowMidHigh = COLORFRONTLOWMIDHIGH_MID
	this.Highlights = &highlights
	return &this
}

// GetBypass returns the Bypass field value if set, zero value otherwise.
func (o *ColorfrontUpmapMode) GetBypass() bool {
	if o == nil || o.Bypass == nil {
		var ret bool
		return ret
	}
	return *o.Bypass
}

// GetBypassOk returns a tuple with the Bypass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColorfrontUpmapMode) GetBypassOk() (*bool, bool) {
	if o == nil || o.Bypass == nil {
		return nil, false
	}
	return o.Bypass, true
}



// HasBypass returns a boolean if a field has been set.
func (o *ColorfrontUpmapMode) HasBypass() bool {
	if o != nil && o.Bypass != nil {
		return true
	}

	return false
}

// SetBypass gets a reference to the given bool and assigns it to the Bypass field.
func (o *ColorfrontUpmapMode) SetBypass(v bool) {
	tmp := v
	o.Bypass = &tmp
}

// GetContrast returns the Contrast field value if set, zero value otherwise.
func (o *ColorfrontUpmapMode) GetContrast() ColorfrontLowMidHigh {
	if o == nil || o.Contrast == nil {
		var ret ColorfrontLowMidHigh
		return ret
	}
	return *o.Contrast
}

// GetContrastOk returns a tuple with the Contrast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColorfrontUpmapMode) GetContrastOk() (*ColorfrontLowMidHigh, bool) {
	if o == nil || o.Contrast == nil {
		return nil, false
	}
	return o.Contrast, true
}



// HasContrast returns a boolean if a field has been set.
func (o *ColorfrontUpmapMode) HasContrast() bool {
	if o != nil && o.Contrast != nil {
		return true
	}

	return false
}

// SetContrast gets a reference to the given ColorfrontLowMidHigh and assigns it to the Contrast field.
func (o *ColorfrontUpmapMode) SetContrast(v ColorfrontLowMidHigh) {
	tmp := v
	o.Contrast = &tmp
}

// GetHighlights returns the Highlights field value if set, zero value otherwise.
func (o *ColorfrontUpmapMode) GetHighlights() ColorfrontLowMidHigh {
	if o == nil || o.Highlights == nil {
		var ret ColorfrontLowMidHigh
		return ret
	}
	return *o.Highlights
}

// GetHighlightsOk returns a tuple with the Highlights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColorfrontUpmapMode) GetHighlightsOk() (*ColorfrontLowMidHigh, bool) {
	if o == nil || o.Highlights == nil {
		return nil, false
	}
	return o.Highlights, true
}



// HasHighlights returns a boolean if a field has been set.
func (o *ColorfrontUpmapMode) HasHighlights() bool {
	if o != nil && o.Highlights != nil {
		return true
	}

	return false
}

// SetHighlights gets a reference to the given ColorfrontLowMidHigh and assigns it to the Highlights field.
func (o *ColorfrontUpmapMode) SetHighlights(v ColorfrontLowMidHigh) {
	tmp := v
	o.Highlights = &tmp
}

func (o ColorfrontUpmapMode) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Bypass != nil {
		toSerialize["bypass"] = o.Bypass
	}
	if o.Contrast != nil {
		toSerialize["contrast"] = o.Contrast
	}
	if o.Highlights != nil {
		toSerialize["highlights"] = o.Highlights
	}
	return json.Marshal(toSerialize)
}


func (o *ColorfrontUpmapMode) ApplyMinMaxConstraints() bool {
	var valueChanged bool = false
	return valueChanged
}

type NullableColorfrontUpmapMode struct {
	value *ColorfrontUpmapMode
	isSet bool
}

func (v NullableColorfrontUpmapMode) Get() *ColorfrontUpmapMode {
	return v.value
}

func (v *NullableColorfrontUpmapMode) Set(val *ColorfrontUpmapMode) {
	v.value = val
	v.isSet = true
}

func (v NullableColorfrontUpmapMode) IsSet() bool {
	return v.isSet
}

func (v *NullableColorfrontUpmapMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColorfrontUpmapMode(val *ColorfrontUpmapMode) *NullableColorfrontUpmapMode {
	return &NullableColorfrontUpmapMode{value: val, isSet: true}
}

func (v NullableColorfrontUpmapMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColorfrontUpmapMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


