/*
OpenAPI ColorBox

This is a REST API for the AJA ColorBox product.

The version of the OpenAPI document: 1.0.0
Contact: support@aja.com

NOTE: This code is auto generated by OpenAPI Generator (https://openapi-generator.tech).
      Do not edit this code manually.

Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
*/

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrionMethod the model 'OrionMethod'
type OrionMethod string

// List of OrionMethod
const (
	ORIONMETHOD_LUMA OrionMethod = "Luma"
	ORIONMETHOD_MAX_RGB OrionMethod = "Max(RGB)"
)

// All allowed values of OrionMethod enum
var AllowedOrionMethodEnumValues = []OrionMethod{
	"Luma",
	"Max(RGB)",
}

func (v *OrionMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrionMethod(value)
	for _, existing := range AllowedOrionMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrionMethod", value)
}

// NewOrionMethodFromValue returns a pointer to a valid OrionMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrionMethodFromValue(v string) (*OrionMethod, error) {
	ev := OrionMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrionMethod: valid values are %v", v, AllowedOrionMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrionMethod) IsValid() bool {
	for _, existing := range AllowedOrionMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrionMethod value
func (v OrionMethod) Ptr() *OrionMethod {
	return &v
}

type NullableOrionMethod struct {
	value *OrionMethod
	isSet bool
}

func (v NullableOrionMethod) Get() *OrionMethod {
	return v.value
}

func (v *NullableOrionMethod) Set(val *OrionMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableOrionMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableOrionMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrionMethod(val *OrionMethod) *NullableOrionMethod {
	return &NullableOrionMethod{value: val, isSet: true}
}

func (v NullableOrionMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrionMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

