/*
OpenAPI ColorBox

This is a REST API for the AJA ColorBox product.

The version of the OpenAPI document: 1.0.0
Contact: support@aja.com

NOTE: This code is auto generated by OpenAPI Generator (https://openapi-generator.tech).
      Do not edit this code manually.

Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
*/

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrionMode the model 'OrionMode'
type OrionMode string

// List of OrionMode
const (
	ORIONMODE_DISPLAY_LIGHT OrionMode = "Display Light"
	ORIONMODE_SCENE_LIGHT OrionMode = "Scene Light"
)

// All allowed values of OrionMode enum
var AllowedOrionModeEnumValues = []OrionMode{
	"Display Light",
	"Scene Light",
}

func (v *OrionMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrionMode(value)
	for _, existing := range AllowedOrionModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrionMode", value)
}

// NewOrionModeFromValue returns a pointer to a valid OrionMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrionModeFromValue(v string) (*OrionMode, error) {
	ev := OrionMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrionMode: valid values are %v", v, AllowedOrionModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrionMode) IsValid() bool {
	for _, existing := range AllowedOrionModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrionMode value
func (v OrionMode) Ptr() *OrionMode {
	return &v
}

type NullableOrionMode struct {
	value *OrionMode
	isSet bool
}

func (v NullableOrionMode) Get() *OrionMode {
	return v.value
}

func (v *NullableOrionMode) Set(val *OrionMode) {
	v.value = val
	v.isSet = true
}

func (v NullableOrionMode) IsSet() bool {
	return v.isSet
}

func (v *NullableOrionMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrionMode(val *OrionMode) *NullableOrionMode {
	return &NullableOrionMode{value: val, isSet: true}
}

func (v NullableOrionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrionMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

