/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OAIAcesConfig.h
 *
 * 
 */

#ifndef OAIAcesConfig_H
#define OAIAcesConfig_H

#include <QJsonObject>

#include "OAIAcesMode.h"
#include "OAIOcioDisplayView.h"
#include "OAIOcioSource.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAcesConfig : public OAIObject {
public:
    OAIAcesConfig();
    OAIAcesConfig(QString json);
    ~OAIAcesConfig() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isEnabled() const;
    void setEnabled(const bool &enabled);
    bool is_enabled_Set() const;
    bool is_enabled_Valid() const;

    OAIAcesMode getMode() const;
    void setMode(const OAIAcesMode &mode);
    bool is_mode_Set() const;
    bool is_mode_Valid() const;

    qint32 getAmfLibraryEntry() const;
    void setAmfLibraryEntry(const qint32 &amf_library_entry);
    bool is_amf_library_entry_Set() const;
    bool is_amf_library_entry_Valid() const;

    OAIOcioSource getOcioSource() const;
    void setOcioSource(const OAIOcioSource &ocio_source);
    bool is_ocio_source_Set() const;
    bool is_ocio_source_Valid() const;

    OAIOcioDisplayView getOcioDisplayView() const;
    void setOcioDisplayView(const OAIOcioDisplayView &ocio_display_view);
    bool is_ocio_display_view_Set() const;
    bool is_ocio_display_view_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    bool m_enabled;
    bool m_enabled_isSet;
    bool m_enabled_isValid;

    OAIAcesMode m_mode;
    bool m_mode_isSet;
    bool m_mode_isValid;

    qint32 m_amf_library_entry;
    bool m_amf_library_entry_isSet;
    bool m_amf_library_entry_isValid;

    OAIOcioSource m_ocio_source;
    bool m_ocio_source_isSet;
    bool m_ocio_source_isValid;

    OAIOcioDisplayView m_ocio_display_view;
    bool m_ocio_display_view_isSet;
    bool m_ocio_display_view_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAcesConfig)

#endif // OAIAcesConfig_H
