/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */

#include "OAIColorfrontDynRangeGamutLiveModeOut.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIColorfrontDynRangeGamutLiveModeOut::OAIColorfrontDynRangeGamutLiveModeOut(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIColorfrontDynRangeGamutLiveModeOut::OAIColorfrontDynRangeGamutLiveModeOut() {
    this->initializeModel();
}

OAIColorfrontDynRangeGamutLiveModeOut::~OAIColorfrontDynRangeGamutLiveModeOut() {}

void OAIColorfrontDynRangeGamutLiveModeOut::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIColorfrontDynRangeGamutLiveModeOut::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIColorfrontDynRangeGamutLiveModeOut::fromJson(QString jsonString) {
    
    if ( jsonString.compare("SDR BT.709 100 Nits", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::SDR_BT_709_100_NITS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("SDR Extended BT.709", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::SDR_EXTENDED_BT_709;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PQ BT.2020 1000 Nits", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::PQ_BT_2020_1000_NITS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PQ P3D65 1000 Nits", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::PQ_P3D65_1000_NITS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("HLG BT.2100", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::HLG_BT_2100;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("HLG Extended BT.709", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::HLG_EXTENDED_BT_709;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("HLG Extended BT.2100", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::HLG_EXTENDED_BT_2100;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Sony SLog3 S-Gamut3", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::SONY_SLOG3_S_GAMUT3;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Sony SLog3 BT.2020", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::SONY_SLOG3_BT_2020;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ARRI Log C Wide Gamut", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::ARRI_LOG_C_WIDE_GAMUT;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ARRI LogC4 Wide Gamut 4", Qt::CaseInsensitive) == 0) {
        m_value = eOAIColorfrontDynRangeGamutLiveModeOut::ARRI_LOGC4_WIDE_GAMUT_4;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIColorfrontDynRangeGamutLiveModeOut::fromJsonValue(QJsonValue json) {
fromJson(json.toString());

    applyMinMaxConstraints();
}

QString OAIColorfrontDynRangeGamutLiveModeOut::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIColorfrontDynRangeGamutLiveModeOut::SDR_BT_709_100_NITS:
            val = "SDR BT.709 100 Nits";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::SDR_EXTENDED_BT_709:
            val = "SDR Extended BT.709";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::PQ_BT_2020_1000_NITS:
            val = "PQ BT.2020 1000 Nits";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::PQ_P3D65_1000_NITS:
            val = "PQ P3D65 1000 Nits";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::HLG_BT_2100:
            val = "HLG BT.2100";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::HLG_EXTENDED_BT_709:
            val = "HLG Extended BT.709";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::HLG_EXTENDED_BT_2100:
            val = "HLG Extended BT.2100";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::SONY_SLOG3_S_GAMUT3:
            val = "Sony SLog3 S-Gamut3";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::SONY_SLOG3_BT_2020:
            val = "Sony SLog3 BT.2020";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::ARRI_LOG_C_WIDE_GAMUT:
            val = "ARRI Log C Wide Gamut";
            break;
        case eOAIColorfrontDynRangeGamutLiveModeOut::ARRI_LOGC4_WIDE_GAMUT_4:
            val = "ARRI LogC4 Wide Gamut 4";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIColorfrontDynRangeGamutLiveModeOut::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIColorfrontDynRangeGamutLiveModeOut::eOAIColorfrontDynRangeGamutLiveModeOut OAIColorfrontDynRangeGamutLiveModeOut::getValue() const {
    return m_value;
}

void OAIColorfrontDynRangeGamutLiveModeOut::setValue(const OAIColorfrontDynRangeGamutLiveModeOut::eOAIColorfrontDynRangeGamutLiveModeOut& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIColorfrontDynRangeGamutLiveModeOut::isSet() const {
    
    return m_value_isSet;
}

bool OAIColorfrontDynRangeGamutLiveModeOut::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

bool OAIColorfrontDynRangeGamutLiveModeOut::applyMinMaxConstraints() {
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

} // namespace OpenAPI
