/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

#include "OAIDHCPState.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDHCPState::OAIDHCPState(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDHCPState::OAIDHCPState() {
    this->initializeModel();
}

OAIDHCPState::~OAIDHCPState() {}

void OAIDHCPState::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIDHCPState::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIDHCPState::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Disabled", Qt::CaseInsensitive) == 0) {
        m_value = eOAIDHCPState::DISABLED;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Discover", Qt::CaseInsensitive) == 0) {
        m_value = eOAIDHCPState::DISCOVER;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Request", Qt::CaseInsensitive) == 0) {
        m_value = eOAIDHCPState::REQUEST;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Bound", Qt::CaseInsensitive) == 0) {
        m_value = eOAIDHCPState::BOUND;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIDHCPState::fromJsonValue(QJsonValue json) {
fromJson(json.toString());

    applyMinMaxConstraints();
}

QString OAIDHCPState::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIDHCPState::DISABLED:
            val = "Disabled";
            break;
        case eOAIDHCPState::DISCOVER:
            val = "Discover";
            break;
        case eOAIDHCPState::REQUEST:
            val = "Request";
            break;
        case eOAIDHCPState::BOUND:
            val = "Bound";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIDHCPState::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIDHCPState::eOAIDHCPState OAIDHCPState::getValue() const {
    return m_value;
}

void OAIDHCPState::setValue(const OAIDHCPState::eOAIDHCPState& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIDHCPState::isSet() const {
    
    return m_value_isSet;
}

bool OAIDHCPState::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

bool OAIDHCPState::applyMinMaxConstraints() {
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

} // namespace OpenAPI
