/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020 AJA Video Systems Inc.  All rights reserved.
 */

#include "OAIOcioDisplayView.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIOcioDisplayView::OAIOcioDisplayView(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIOcioDisplayView::OAIOcioDisplayView() {
    this->initializeModel();
}

OAIOcioDisplayView::~OAIOcioDisplayView() {}

void OAIOcioDisplayView::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIOcioDisplayView::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIOcioDisplayView::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Rec.1886 Rec.709 - Display/ACES 1.0 - SDR Video", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::REC_1886_REC_709_DISPLAY_ACES_1_0_SDR_VIDEO;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Rec.2100-HLG - Display/ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::REC_2100_HLG_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_REC_2020_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Rec.2100-PQ - Display/ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_REC_2020_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Rec.2100-PQ - Display/ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_2000_NITS_REC_2020_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Rec.2100-PQ - Display/ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_4000_NITS_REC_2020_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (1000 nits & P3 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_P3_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (2000 nits & P3 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_2000_NITS_P3_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (4000 nits & P3 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_4000_NITS_P3_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ST2084-P3-D65 - Display/ACES 1.1 - HDR Cinema (108 nits & P3 lim)", Qt::CaseInsensitive) == 0) {
        m_value = eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_CINEMA_108_NITS_P3_LIM_;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIOcioDisplayView::fromJsonValue(QJsonValue json) {
fromJson(json.toString());

    applyMinMaxConstraints();
}

QString OAIOcioDisplayView::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIOcioDisplayView::REC_1886_REC_709_DISPLAY_ACES_1_0_SDR_VIDEO:
            val = "Rec.1886 Rec.709 - Display/ACES 1.0 - SDR Video";
            break;
        case eOAIOcioDisplayView::REC_2100_HLG_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_REC_2020_LIM_:
            val = "Rec.2100-HLG - Display/ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)";
            break;
        case eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_REC_2020_LIM_:
            val = "Rec.2100-PQ - Display/ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)";
            break;
        case eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_2000_NITS_REC_2020_LIM_:
            val = "Rec.2100-PQ - Display/ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim)";
            break;
        case eOAIOcioDisplayView::REC_2100_PQ_DISPLAY_ACES_1_1_HDR_VIDEO_4000_NITS_REC_2020_LIM_:
            val = "Rec.2100-PQ - Display/ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)";
            break;
        case eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_1000_NITS_P3_LIM_:
            val = "ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (1000 nits & P3 lim)";
            break;
        case eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_2000_NITS_P3_LIM_:
            val = "ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (2000 nits & P3 lim)";
            break;
        case eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_VIDEO_4000_NITS_P3_LIM_:
            val = "ST2084-P3-D65 - Display/ACES 1.1 - HDR Video (4000 nits & P3 lim)";
            break;
        case eOAIOcioDisplayView::ST2084_P3_D65_DISPLAY_ACES_1_1_HDR_CINEMA_108_NITS_P3_LIM_:
            val = "ST2084-P3-D65 - Display/ACES 1.1 - HDR Cinema (108 nits & P3 lim)";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIOcioDisplayView::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIOcioDisplayView::eOAIOcioDisplayView OAIOcioDisplayView::getValue() const {
    return m_value;
}

void OAIOcioDisplayView::setValue(const OAIOcioDisplayView::eOAIOcioDisplayView& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIOcioDisplayView::isSet() const {
    
    return m_value_isSet;
}

bool OAIOcioDisplayView::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

bool OAIOcioDisplayView::applyMinMaxConstraints() {
	bool anyMinMaxValueChanged = false;
	return anyMinMaxValueChanged;
}

} // namespace OpenAPI
