/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OAIPatternRect.h
 *
 * 
 */

#ifndef OAIPatternRect_H
#define OAIPatternRect_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPatternRect : public OAIObject {
public:
    OAIPatternRect();
    OAIPatternRect(QString json);
    ~OAIPatternRect() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getXstart() const;
    void setXstart(const double &xstart);
    bool is_xstart_Set() const;
    bool is_xstart_Valid() const;
    double xstartMin() const;
    double xstartMax() const;

    double getYstart() const;
    void setYstart(const double &ystart);
    bool is_ystart_Set() const;
    bool is_ystart_Valid() const;
    double ystartMin() const;
    double ystartMax() const;

    double getWidth() const;
    void setWidth(const double &width);
    bool is_width_Set() const;
    bool is_width_Valid() const;
    double widthMin() const;
    double widthMax() const;

    double getHeight() const;
    void setHeight(const double &height);
    bool is_height_Set() const;
    bool is_height_Valid() const;
    double heightMin() const;
    double heightMax() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    double m_xstart;
    bool m_xstart_isSet;
    bool m_xstart_isValid;

    double m_ystart;
    bool m_ystart_isSet;
    bool m_ystart_isValid;

    double m_width;
    bool m_width_isSet;
    bool m_width_isValid;

    double m_height;
    bool m_height_isSet;
    bool m_height_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPatternRect)

#endif // OAIPatternRect_H
