/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OAIPatternColor.h
 *
 * 
 */

#ifndef OAIPatternColor_H
#define OAIPatternColor_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPatternColor : public OAIObject {
public:
    OAIPatternColor();
    OAIPatternColor(QString json);
    ~OAIPatternColor() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getDepth() const;
    void setDepth(const qint32 &depth);
    bool is_depth_Set() const;
    bool is_depth_Valid() const;
    qint32 depthMin() const;
    qint32 depthMax() const;

    qint32 getBlue() const;
    void setBlue(const qint32 &blue);
    bool is_blue_Set() const;
    bool is_blue_Valid() const;
    qint32 blueMin() const;
    qint32 blueMax() const;

    qint32 getGreen() const;
    void setGreen(const qint32 &green);
    bool is_green_Set() const;
    bool is_green_Valid() const;
    qint32 greenMin() const;
    qint32 greenMax() const;

    qint32 getRed() const;
    void setRed(const qint32 &red);
    bool is_red_Set() const;
    bool is_red_Valid() const;
    qint32 redMin() const;
    qint32 redMax() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    qint32 m_depth;
    bool m_depth_isSet;
    bool m_depth_isValid;

    qint32 m_blue;
    bool m_blue_isSet;
    bool m_blue_isValid;

    qint32 m_green;
    bool m_green_isSet;
    bool m_green_isValid;

    qint32 m_red;
    bool m_red_isSet;
    bool m_red_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPatternColor)

#endif // OAIPatternColor_H
