/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

/*
 * OAIStatusState.h
 *
 * The good/maybe/bad/unknown of the status object
 */

#ifndef OAIStatusState_H
#define OAIStatusState_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStatusState : public OAIEnum {
public:
    OAIStatusState();
    OAIStatusState(QString json);
    ~OAIStatusState() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIStatusState {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        STATUSSTATEGOOD, 
        STATUSSTATEMAYBE, 
        STATUSSTATEBAD, 
        STATUSSTATEUNKNOWN
    };
    OAIStatusState::eOAIStatusState getValue() const;
    void setValue(const OAIStatusState::eOAIStatusState& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    eOAIStatusState m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStatusState)

#endif // OAIStatusState_H
