/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OAIStage.h
 *
 * 
 */

#ifndef OAIStage_H
#define OAIStage_H

#include <QJsonObject>

#include "OAIColorCorrector.h"
#include "OAIProcAmp.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStage : public OAIObject {
public:
    OAIStage();
    OAIStage(QString json);
    ~OAIStage() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isEnabled() const;
    void setEnabled(const bool &enabled);
    bool is_enabled_Set() const;
    bool is_enabled_Valid() const;

    bool isDynamic() const;
    void setDynamic(const bool &dynamic);
    bool is_dynamic_Set() const;
    bool is_dynamic_Valid() const;

    qint32 getLibraryEntry() const;
    void setLibraryEntry(const qint32 &library_entry);
    bool is_library_entry_Set() const;
    bool is_library_entry_Valid() const;

    OAIColorCorrector getColorCorrector() const;
    void setColorCorrector(const OAIColorCorrector &color_corrector);
    bool is_color_corrector_Set() const;
    bool is_color_corrector_Valid() const;

    OAIProcAmp getProcAmp() const;
    void setProcAmp(const OAIProcAmp &proc_amp);
    bool is_proc_amp_Set() const;
    bool is_proc_amp_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    bool m_enabled;
    bool m_enabled_isSet;
    bool m_enabled_isValid;

    bool m_dynamic;
    bool m_dynamic_isSet;
    bool m_dynamic_isValid;

    qint32 m_library_entry;
    bool m_library_entry_isSet;
    bool m_library_entry_isValid;

    OAIColorCorrector m_color_corrector;
    bool m_color_corrector_isSet;
    bool m_color_corrector_isValid;

    OAIProcAmp m_proc_amp;
    bool m_proc_amp_isSet;
    bool m_proc_amp_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStage)

#endif // OAIStage_H
