/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
 */

/*
 * OAISystemStatus.h
 *
 * 
 */

#ifndef OAISystemStatus_H
#define OAISystemStatus_H

#include <QJsonObject>

#include <QDateTime>
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISystemStatus : public OAIObject {
public:
    OAISystemStatus();
    OAISystemStatus(QString json);
    ~OAISystemStatus() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getSafebootVersion() const;
    void setSafebootVersion(const QString &safeboot_version);
    bool is_safeboot_version_Set() const;
    bool is_safeboot_version_Valid() const;

    QString getMainbootVersion() const;
    void setMainbootVersion(const QString &mainboot_version);
    bool is_mainboot_version_Set() const;
    bool is_mainboot_version_Valid() const;

    QString getRunningVersion() const;
    void setRunningVersion(const QString &running_version);
    bool is_running_version_Set() const;
    bool is_running_version_Valid() const;

    bool isSafeboot() const;
    void setSafeboot(const bool &safeboot);
    bool is_safeboot_Set() const;
    bool is_safeboot_Valid() const;

    QList<QString> getUpdateMsg() const;
    void setUpdateMsg(const QList<QString> &update_msg);
    bool is_update_msg_Set() const;
    bool is_update_msg_Valid() const;

    bool isTransformModeChanging() const;
    void setTransformModeChanging(const bool &transform_mode_changing);
    bool is_transform_mode_changing_Set() const;
    bool is_transform_mode_changing_Valid() const;

    QDateTime getTransformModeTimestamp() const;
    void setTransformModeTimestamp(const QDateTime &transform_mode_timestamp);
    bool is_transform_mode_timestamp_Set() const;
    bool is_transform_mode_timestamp_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    QString m_safeboot_version;
    bool m_safeboot_version_isSet;
    bool m_safeboot_version_isValid;

    QString m_mainboot_version;
    bool m_mainboot_version_isSet;
    bool m_mainboot_version_isValid;

    QString m_running_version;
    bool m_running_version_isSet;
    bool m_running_version_isValid;

    bool m_safeboot;
    bool m_safeboot_isSet;
    bool m_safeboot_isValid;

    QList<QString> m_update_msg;
    bool m_update_msg_isSet;
    bool m_update_msg_isValid;

    bool m_transform_mode_changing;
    bool m_transform_mode_changing_isSet;
    bool m_transform_mode_changing_isValid;

    QDateTime m_transform_mode_timestamp;
    bool m_transform_mode_timestamp_isSet;
    bool m_transform_mode_timestamp_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISystemStatus)

#endif // OAISystemStatus_H
