/**
 * OpenAPI ColorBox
 * This is a REST API for the AJA ColorBox product.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@aja.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *       Do not edit the class manually.
 *
 * Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
 */

/*
 * OAIWiFiDeviceStatus.h
 *
 * 
 */

#ifndef OAIWiFiDeviceStatus_H
#define OAIWiFiDeviceStatus_H

#include <QJsonObject>

#include "OAIDHCPState.h"
#include "OAIInterfaceSetupState.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIWiFiDeviceStatus : public OAIObject {
public:
    OAIWiFiDeviceStatus();
    OAIWiFiDeviceStatus(QString json);
    ~OAIWiFiDeviceStatus() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getMac() const;
    void setMac(const QString &mac);
    bool is_mac_Set() const;
    bool is_mac_Valid() const;

    QString getAddress() const;
    void setAddress(const QString &address);
    bool is_address_Set() const;
    bool is_address_Valid() const;

    QString getSubnet() const;
    void setSubnet(const QString &subnet);
    bool is_subnet_Set() const;
    bool is_subnet_Valid() const;

    QString getGateway() const;
    void setGateway(const QString &gateway);
    bool is_gateway_Set() const;
    bool is_gateway_Valid() const;

    QList<QString> getNetworks() const;
    void setNetworks(const QList<QString> &networks);
    bool is_networks_Set() const;
    bool is_networks_Valid() const;

    bool isConnected() const;
    void setConnected(const bool &connected);
    bool is_connected_Set() const;
    bool is_connected_Valid() const;

    OAIDHCPState getDhcpState() const;
    void setDhcpState(const OAIDHCPState &dhcp_state);
    bool is_dhcp_state_Set() const;
    bool is_dhcp_state_Valid() const;

    OAIInterfaceSetupState getInterfaceSetupState() const;
    void setInterfaceSetupState(const OAIInterfaceSetupState &interface_setup_state);
    bool is_interface_setup_state_Set() const;
    bool is_interface_setup_state_Valid() const;

    QString getIpAddressOffered() const;
    void setIpAddressOffered(const QString &ip_address_offered);
    bool is_ip_address_offered_Set() const;
    bool is_ip_address_offered_Valid() const;

    QString getLinkState() const;
    void setLinkState(const QString &link_state);
    bool is_link_state_Set() const;
    bool is_link_state_Valid() const;

    QString getWifiDongleState() const;
    void setWifiDongleState(const QString &wifi_dongle_state);
    bool is_wifi_dongle_state_Set() const;
    bool is_wifi_dongle_state_Valid() const;

    QString getAuthenticationState() const;
    void setAuthenticationState(const QString &authentication_state);
    bool is_authentication_state_Set() const;
    bool is_authentication_state_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

    bool applyMinMaxConstraints();
private:
    void initializeModel();

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString m_mac;
    bool m_mac_isSet;
    bool m_mac_isValid;

    QString m_address;
    bool m_address_isSet;
    bool m_address_isValid;

    QString m_subnet;
    bool m_subnet_isSet;
    bool m_subnet_isValid;

    QString m_gateway;
    bool m_gateway_isSet;
    bool m_gateway_isValid;

    QList<QString> m_networks;
    bool m_networks_isSet;
    bool m_networks_isValid;

    bool m_connected;
    bool m_connected_isSet;
    bool m_connected_isValid;

    OAIDHCPState m_dhcp_state;
    bool m_dhcp_state_isSet;
    bool m_dhcp_state_isValid;

    OAIInterfaceSetupState m_interface_setup_state;
    bool m_interface_setup_state_isSet;
    bool m_interface_setup_state_isValid;

    QString m_ip_address_offered;
    bool m_ip_address_offered_isSet;
    bool m_ip_address_offered_isValid;

    QString m_link_state;
    bool m_link_state_isSet;
    bool m_link_state_isValid;

    QString m_wifi_dongle_state;
    bool m_wifi_dongle_state_isSet;
    bool m_wifi_dongle_state_isValid;

    QString m_authentication_state;
    bool m_authentication_state_isSet;
    bool m_authentication_state_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIWiFiDeviceStatus)

#endif // OAIWiFiDeviceStatus_H
