"""
    OpenAPI Soji

    This is a REST API for the AJA Soji product.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@aja.com
    NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
          Do not edit the class manually.
    	  
    Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
"""


import sys
import unittest

import openapi_client
from openapi_client.model.orion_clamping import OrionClamping
from openapi_client.model.orion_conversion import OrionConversion
from openapi_client.model.orion_implementation import OrionImplementation
from openapi_client.model.orion_method import OrionMethod
from openapi_client.model.orion_mode import OrionMode
from openapi_client.model.orion_sdr_eotf import OrionSdrEotf
from openapi_client.model.orion_source_range import OrionSourceRange
globals()['OrionClamping'] = OrionClamping
globals()['OrionConversion'] = OrionConversion
globals()['OrionImplementation'] = OrionImplementation
globals()['OrionMethod'] = OrionMethod
globals()['OrionMode'] = OrionMode
globals()['OrionSdrEotf'] = OrionSdrEotf
globals()['OrionSourceRange'] = OrionSourceRange
from openapi_client.model.orion_config import OrionConfig


class TestOrionConfig(unittest.TestCase):
    """OrionConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrionConfig(self):
        """Test OrionConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrionConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
