"""
    OpenAPI ColorBox

    This is a REST API for the AJA ColorBox product.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@aja.com
    NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
          Do not edit the class manually.

    Copyright (C) 2020-2022 AJA Video Systems Inc.  All rights reserved.
"""


import sys
import unittest

import openapi_client
from openapi_client.model.stage import Stage
globals()['Stage'] = Stage
from openapi_client.model.bbc_config import BbcConfig


class TestBbcConfig(unittest.TestCase):
    """BbcConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBbcConfig(self):
        """Test BbcConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BbcConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
