"""
    OpenAPI ColorBox

    This is a REST API for the AJA ColorBox product.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@aja.com
    NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
          Do not edit the class manually.

    Copyright (C) 2020-2022 AJA Video Systems, Inc.  All rights reserved.
"""


import sys
import unittest

import openapi_client
from openapi_client.model.file_type_choice import FileTypeChoice


class TestFileTypeChoice(unittest.TestCase):
    """FileTypeChoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileTypeChoice(self):
        """Test FileTypeChoice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileTypeChoice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
